[workspace]
members = [
  # all crates in a `./crates` folder will be added to the workspace
  "crates/*",
]
resolver = "2"

[workspace.dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
either = "1.13"
futures = "0.3"
itertools = "*"
miette = "7.2"
ordered-float = { version = "4.2", features = ["serde", "rand"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["fs"] }
tokio-util = "0.7.9"
