#+HTML: <p align="center">
#+HTML:   <img src="stuff/rumps-title.svg" alt="R U M P S" width="800">
#+HTML: </p>

#+HTML: <hr style="border:0; border-top:1px solid #bbb; margin-top:0.4em; margin-bottom:1.2em;">

* Table of Contents :toc@2@gh:
- [[#introduction][Introduction]]
  - [[#quick-start][Quick start]]
- [[#wtf-is-rumps][WTF is RUMPS?]]
  - [[#mumps][MUMPS]]
  - [[#core-concepts][Core concepts]]
- [[#using-rumps][Using RUMPS]]
  - [[#core-operations][Core operations]]
  - [[#rust-api][Rust API]]
  - [[#query-language][Query language]]
- [[#use-cases][Use cases]]
  - [[#where-rumps-is-a-good-fit][Where RUMPS is a good fit]]
  - [[#where-rumps-is-a-bad-fit][Where RUMPS is a bad fit]]
- [[#comparison-to-other-database-systems][Comparison to other database systems]]
- [[#licenses][License(s)]]
- [[#disclaimer][Disclaimer]]

* Introduction
*RUMPS* is a re-imagining of MUMPS-style database systems. It diverges quite a bit from traditional MUMPS, particularly in its (WIP) query language, explicit transaction support, etc... Read on to find out more. If you don't know what MUMPS is, [[https://en.wikipedia.org/wiki/MUMPS][this]] is a good introduction. RUMPS has many of MUMPS' core concepts, e.g. collation order, a similar storage model, etc..., but either expands on or diverges wildly from them. RUMPS is a bit of a bizarre mishmash of MUMPS, SQLite (more so when the query language is done), and something else. See [[#wtf-is-rumps][WTF is RUMPS?]] for more details.
** Quick start
*** Rust API
1. Get RUMPS somehow
   - *NOTE*: I haven't put any of the RUMPS crates on ~crates.io~ yet, so you'll need to use it as a Git crate
2. Start writing your sweet, sweet data to RUMPS; this is a minimal example: much more explanation is below on the different operations:
  #+begin_src rust
  use futures::TryStreamExt;
  use rumps::{Database, DataStatus, Key, Subscript, global, key, value};

  // NOTE: RUMPS is fully async, as also explained below; currently, it only
  // supports `tokio`
  #[tokio::main]
  async fn main() -> rumps::Result<()> {
      // Create a persistent database
      let db = Database::create("./my_data").await?;

      // Writes to globals require a transaction
      db.transaction(|txn| async move {
          // Insert patients out of order
          txn.set(&global!("PATIENT"), &key![3, "NAME"], value!("carol")).await?;
          txn.set(&global!("PATIENT"), &key![1, "NAME"], value!("alice")).await?;
          txn.set(&global!("PATIENT"), &key![2, "NAME"], value!("bob")).await?;
          Ok(())
      }).await?;

      // All reads work outside transactions
      let name = db.get(&global!("PATIENT"), &key![1, "NAME"]).await?;
      assert_eq!(name, Some(value!("alice")));

      // `ORDER`: get next key in sorted order
      let first = db.order(&global!("PATIENT"), None).await?;
      assert_eq!(first, Some(key![1, "NAME"]));

      // `DATA`: check if a node has value/descendants
      let status = db.data(&global!("PATIENT"), &key![1]).await?;
      assert_eq!(status, DataStatus::HasDescendants);

      // `COLLECT`: stream records - ALWAYS yields in sorted key order;
      // sorting is inherent to RUMPS data storage
      let names: Vec<String> = db
          .collects(
              &global!("PATIENT"),
              None,
              // Predicate to extract data
              |k, _| k.len() == 2 && k.get(1) == Some(&Subscript::from("NAME")),
              // Mapping/transformation of data
              |_, v| v.as_ref()?.as_str().map(str::to_uppercase),
          )
          .await?
          .try_collect()
          .await?;

      // Results come out sorted by _key_, _not_ insertion order
      assert_eq!(names, vec!["ALICE", "BOB", "CAROL"]);

      Ok(())
  }
  #+end_src
*** Query language
*WIP*: The query language is nowhere near completion
* WTF is RUMPS?
** MUMPS
** Core concepts
*** "Variables"
*** Collation order
*** RUMPS-specific things
**** Async first
**** ACID guarantees
***** In-memory: ACI
**** Expanded types and collation order
* Using RUMPS
** Core operations
*** =GET=
*** =SET=
*** =KILL=
*** =DATA=
*** =ORDER=
*** =COLLECT=
** Rust API
*** "ORM" API
** Query language
*WIP*. Nowhere near done. RUMPS can only be used from Rust at the moment.
* Use cases
** Where RUMPS is a good fit
** Where RUMPS is a bad fit
* Comparison to other database systems
* License(s)
Licensed under either of [[file:LICENSES/APACHE][Apache License, Version 2.0]] or [[file:LICENSES/MIT][MIT license]] at your option.
* Disclaimer
