[package]
name = "rumps-query"
version = "0.0.1"
edition = "2021"

[dependencies]
rumps-types = { path = "../rumps-types" }
rumps-storage = { path = "../rumps-storage" }
# rumps-query-macros = { path = "../rumps-query-macros" }
async-recursion = { workspace = true }
async-trait = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
chumsky = "0.9"
miette = { workspace = true }
nonempty = { workspace = true }
futures = { workspace = true }
indexmap = "2"
itertools = { workspace = true }
rand = "0.8"
regex = "1"
unicode-segmentation = { workspace = true }
uuid = { version = "1", features = ["v4"] }
ordered-float = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
datatest-stable = "0.2"
insta = "1.41"
tokio-test = "0.4"

[[test]]
name = "scripts"
harness = false

[lints.clippy]
obfuscated_if_else = "allow"
option_map_unit_fn = "allow"
type_complexity = "allow"
use_self = "warn"
unwrap_used = "deny"
expect_used = "deny"
