//! Type inference context and constraint generation.
//!
//! The inference context tracks type information during type checking:
//! expression types, type variable generation, and constraint collection.
//! Constraints are solved later via unification.

#![allow(clippy::large_enum_variant)]
use std::collections::HashMap;

use smallvec::SmallVec;

use super::env::TypeEnv;
use super::error::TypeError;
use super::ty::{Ty, TyVar};
use crate::ast::{
    Ast, AstTypeExpr, AstTypeExprId, BinOp, Expr, ExprId, JsonAccessKey,
    JsonAccessKind, Literal, UnOp,
};
use crate::intern::StringId;
use crate::value::{TypeDef, TypeId, TypeRegistry};
use crate::Span;

/// A type constraint generated during inference.
///
/// Constraints represent relationships between types that must hold for the
/// program to be well-typed. They are collected during the inference pass
/// and solved together via unification.
#[derive(Clone, Debug)]
pub(crate) enum Constraint {
    /// Two types must be equal.
    ///
    /// Generated by assignments, function return types, binary operators
    /// requiring matching operand types, etc.
    ///
    /// Example: `LET x: Int = e` generates `Eq(typeof(e), Int)`.
    Eq(Ty, Ty, Span),

    /// Type must be numeric (`Int` or `Float`).
    ///
    /// Generated by arithmetic operators (`+`, `-`, `*`, `/`, `%`, `**`)
    /// and unary negation. Numeric coercion (`Int` + `Float` = `Float`)
    /// is handled during constraint solving.
    ///
    /// Example: `a + b` generates `Numeric(typeof(a))` and `Numeric(typeof(b))`.
    Numeric(Ty, Span),

    /// Type must be callable with given argument types.
    ///
    /// Generated by function call expressions. During solving, the callee
    /// type is unified with `Fn(args, ret)`.
    ///
    /// Example: `f(x, y)` generates `Callable { callee: typeof(f), args: [typeof(x), typeof(y)], ret: ?r }`.
    Callable {
        callee: Ty,
        args: SmallVec<[Ty; 4]>,
        ret: Ty,
        span: Span,
    },

    /// Type can be converted to a string for display.
    ///
    /// Generated by string concatenation (`++`) and `OUTPUT` statements.
    /// In RUMPS, all types satisfy this constraint; it exists primarily
    /// to mark where implicit string coercion occurs.
    ///
    /// Example: `OUTPUT x` generates `Stringable(typeof(x))`.
    Stringable(Ty, Span),

    /// Type can be converted to JSON.
    ///
    /// Generated by `AS Json` casts, database `SET` operations, and JSON
    /// literals. Closures and functions cannot be serialized to JSON.
    ///
    /// Allowed: primitives, arrays, tuples, objects, `Option`, `Result`.
    /// Rejected: `Fn`, module functions.
    ///
    /// Example: `x AS Json` generates `Jsonable(typeof(x))`.
    Jsonable(Ty, Span),

    /// Type can be used as a database subscript key.
    ///
    /// Generated by `GET`/`SET` operations with subscripts. Valid subscript
    /// types are: `Bool`, `Int`, `Float`, `Char`, `String`, `Json`.
    ///
    /// Example: `GET local(k)` generates `Subscript(typeof(k))`.
    Subscript(Ty, Span),

    /// Type can be stored in the database.
    ///
    /// Generated by `SET` operations for the value being stored. Valid
    /// storable types match the `Storable` union: `Bool`, `Int`, `Float`,
    /// `Char`, `String`, `Json`.
    ///
    /// Example: `SET local(k) = v` generates `Storable(typeof(v))`.
    Storable(Ty, Span),

    /// Type must be unwrappable via postfix `!`.
    ///
    /// Generated by `e!` expressions. The type must be `Option[T]` or
    /// `Result[T, E]`. The `inner` field captures the extracted inner
    /// type (`T`), which becomes the result type of the unwrap.
    ///
    /// Example: `opt!` generates `Unwrappable { ty: typeof(opt), inner: ?t }`,
    /// and the expression types as `?t`.
    Unwrappable { ty: Ty, inner: Ty, span: Span },
}

impl Constraint {
    /// Get the source span associated with this constraint.
    pub(crate) fn span(&self) -> Span {
        match self {
            Self::Eq(_, _, span)
            | Self::Numeric(_, span)
            | Self::Callable { span, .. }
            | Self::Stringable(_, span)
            | Self::Jsonable(_, span)
            | Self::Subscript(_, span)
            | Self::Storable(_, span)
            | Self::Unwrappable { span, .. } => *span,
        }
    }
}

/// Type inference context.
///
/// Collects type information during the inference pass: inferred expression
/// types, type variable bindings, and constraints. After inference completes,
/// constraints are solved via unification to produce final types.
pub(crate) struct InferCtx<'a> {
    /// The AST being type-checked.
    ast: &'a Ast,
    /// Registry of user-defined and builtin types.
    registry: &'a TypeRegistry,
    /// Scoped type environment (variable -> scheme bindings).
    env: TypeEnv,
    /// Collected constraints to be solved.
    constraints: Vec<Constraint>,
    /// Counter for generating fresh type variables.
    next_var: u32,
    /// Inferred types for each expression.
    expr_types: HashMap<ExprId, Ty>,
    /// Type errors encountered during inference.
    errors: Vec<TypeError>,
}

impl<'a> InferCtx<'a> {
    /// Create a new inference context.
    pub(crate) fn new(ast: &'a Ast, registry: &'a TypeRegistry) -> Self {
        Self {
            ast,
            registry,
            env: TypeEnv::new(),
            constraints: Vec::new(),
            next_var: 0,
            expr_types: HashMap::new(),
            errors: Vec::new(),
        }
    }

    /// Generate a fresh type variable.
    pub(crate) fn fresh_var(&mut self) -> TyVar {
        let v = TyVar::new(self.next_var);
        self.next_var += 1;
        v
    }

    /// Generate a fresh type variable wrapped in `Ty::Var`.
    pub(crate) fn fresh(&mut self) -> Ty {
        Ty::Var(self.fresh_var())
    }

    /// Add a constraint to the collection.
    pub(crate) fn constrain(&mut self, c: Constraint) {
        self.constraints.push(c);
    }

    /// Add an equality constraint between two types.
    ///
    /// Shorthand for `constrain(Constraint::Eq(t1, t2, span))`.
    pub(crate) fn unify(&mut self, t1: Ty, t2: Ty, span: Span) {
        self.constrain(Constraint::Eq(t1, t2, span));
    }

    /// Record the inferred type for an expression.
    pub(crate) fn record_type(&mut self, id: ExprId, ty: Ty) {
        self.expr_types.insert(id, ty);
    }

    /// Record a type error.
    pub(crate) fn error(&mut self, e: TypeError) {
        self.errors.push(e);
    }

    /// Get the AST being type-checked.
    pub(crate) fn ast(&self) -> &Ast {
        self.ast
    }

    /// Get the type registry.
    pub(crate) fn registry(&self) -> &TypeRegistry {
        self.registry
    }

    /// Get a mutable reference to the type environment.
    pub(crate) fn env_mut(&mut self) -> &mut TypeEnv {
        &mut self.env
    }

    /// Get an immutable reference to the type environment.
    pub(crate) fn env(&self) -> &TypeEnv {
        &self.env
    }

    /// Get the next type variable counter (for scheme instantiation).
    pub(crate) fn next_var_mut(&mut self) -> &mut u32 {
        &mut self.next_var
    }

    /// Get the collected constraints.
    pub(crate) fn constraints(&self) -> &[Constraint] {
        &self.constraints
    }

    /// Take ownership of collected constraints, leaving an empty vec.
    pub(crate) fn take_constraints(&mut self) -> Vec<Constraint> {
        std::mem::take(&mut self.constraints)
    }

    /// Get the inferred type for an expression, if recorded.
    pub(crate) fn get_type(&self, id: ExprId) -> Option<&Ty> {
        self.expr_types.get(&id)
    }

    /// Get all expression types.
    pub(crate) fn expr_types(&self) -> &HashMap<ExprId, Ty> {
        &self.expr_types
    }

    /// Check if any errors were recorded.
    pub(crate) fn has_errors(&self) -> bool {
        !self.errors.is_empty()
    }

    /// Get the collected errors.
    pub(crate) fn errors(&self) -> &[TypeError] {
        &self.errors
    }

    /// Take ownership of collected errors, leaving an empty vec.
    pub(crate) fn take_errors(&mut self) -> Vec<TypeError> {
        std::mem::take(&mut self.errors)
    }

    /// Expand a union type to its member types.
    ///
    /// Returns `Some(members)` for union types, `None` for non-unions.
    ///
    /// # Union Representations
    ///
    /// - **Anonymous unions** (`Ty::Union`): Members returned directly.
    /// - **Named unions** (`Ty::Named` with `TypeDef::Union`): Members looked up
    ///   from registry. Builtin unions (`Storable`, `Scalar`) are hardcoded;
    ///   user-defined unions require `TypeExprArena` (Phase 4.14).
    ///
    /// Named unions use `Ty::Named` (not `Ty::Union`) to preserve nominal
    /// identity. This matters for `Storable`'s special `AS` semantics: casting
    /// `x AS Storable` is infallible at compile time but may fail at runtime
    /// with `Error::RuntimeType`. See `Ty::Union` docs for full rationale.
    pub(crate) fn expand_union_members(&self, ty: &Ty) -> Option<Vec<Ty>> {
        match ty {
            Ty::Union(members) => Some(members.clone()),
            Ty::Named(id, _params) => {
                // Handle builtin unions by their known members
                if *id == TypeId::STORABLE {
                    Some(Ty::STORABLE_MEMBERS.to_vec())
                } else if *id == TypeId::SCALAR {
                    Some(Ty::SCALAR_MEMBERS.to_vec())
                } else {
                    // Check if it's a user-defined union
                    self.registry.get_def(*id).and_then(|def| match def {
                        TypeDef::Union { .. } => {
                            // TODO: Resolve member TypeExprIds to Ty when
                            // TypeExprArena is available (Phase 4.14)
                            None
                        }
                        _ => None,
                    })
                }
            }
            _ => None,
        }
    }

    /// Check if a type is a member of a union.
    ///
    /// Returns `true` if `member` is one of the types in `union_ty`.
    pub(crate) fn is_union_member(&self, union_ty: &Ty, member: &Ty) -> bool {
        self.expand_union_members(union_ty)
            .is_some_and(|members| members.iter().any(|m| m == member))
    }

    /// Infer the type of an expression.
    ///
    /// Records the inferred type in `expr_types` and returns it. For undefined
    /// variables, records an error and returns `Ty::Error` for recovery.
    ///
    /// Currently handles Phase 4.3 expressions (literals and variables).
    /// Other expression types will be added in subsequent phases.
    pub(crate) fn infer_expr(&mut self, id: ExprId) -> Ty {
        let span = self.ast.expr_span(id).unwrap_or(Span::new(0, 0));
        let ty = self.ast.get_expr(id).map_or_else(
            || Ty::Error,
            |expr| self.infer_expr_inner(expr, span),
        );
        self.record_type(id, ty.clone());
        ty
    }

    /// Inner expression inference; dispatches on expression variant.
    fn infer_expr_inner(&mut self, expr: &Expr, span: Span) -> Ty {
        match expr {
            // Literals
            Expr::Literal(lit) => self.infer_literal(lit),

            // Unit: empty tuple
            Expr::Tuple(elems) if elems.is_empty() => Ty::Unit,

            // Variable reference
            Expr::Var(name) => self.infer_var(name, span),

            // Binary operations
            Expr::Binary(lhs, op, rhs) => {
                self.infer_binary(*lhs, *op, *rhs, span)
            }

            // Unary operations
            Expr::Unary(op, operand) => self.infer_unary(*op, *operand, span),

            // Range expressions
            Expr::Range(start, end, _inclusive) => {
                let start_ty = self.infer_expr(*start);
                let end_ty = self.infer_expr(*end);
                self.unify(start_ty, Ty::Int, span);
                self.unify(end_ty, Ty::Int, span);
                Ty::Range
            }

            // Arrays
            Expr::Array(elems) => self.infer_array(elems, span),

            // Non-empty tuples (empty handled above as Unit)
            Expr::Tuple(elems) => self.infer_tuple(elems),

            // Structural objects
            Expr::Object(fields) => self.infer_object(fields),

            // Map literals
            Expr::MapLit(entries) => self.infer_map_lit(entries, span),

            // Field access: obj.field
            Expr::Field(base, field) => self.infer_field(*base, field, span),

            // Optional field access: obj?.field
            Expr::OptionalField(base, field) => {
                self.infer_optional_field(*base, field, span)
            }

            // Tuple index: tuple.0, tuple.1, etc.
            Expr::TupleIndex(base, idx) => {
                self.infer_tuple_index(*base, *idx, span)
            }

            // Index access: arr[i] or map[k]
            Expr::Index(base, idx) => self.infer_index(*base, *idx, span),

            // JSON access: data.field, data..field, data->"key", data->>"key"
            Expr::JsonAccess(base, kind, key) => {
                self.infer_json_access(*base, kind, key, span)
            }

            // JSON literals
            Expr::Json(_) => Ty::Json,

            // Other expressions handled in later phases
            _ => Ty::Error,
        }
    }

    /// Infer type of a literal.
    fn infer_literal(&self, lit: &Literal) -> Ty {
        match lit {
            Literal::Bool(_) => Ty::Bool,
            Literal::Int(_) => Ty::Int,
            Literal::Float(_) => Ty::Float,
            Literal::Char(_) => Ty::Char,
            Literal::String(_) => Ty::String,
            Literal::Null => Ty::Json,
            Literal::Unit => Ty::Unit,
        }
    }

    /// Infer type of a variable reference.
    ///
    /// Looks up the variable in the type environment and instantiates its
    /// scheme with fresh type variables. If undefined, records an error
    /// and returns `Ty::Error`.
    fn infer_var(&mut self, name: &str, span: Span) -> Ty {
        match self.env.lookup(name) {
            Some(scheme) => scheme.instantiate(&mut self.next_var),
            None => {
                self.error(TypeError::UndefinedVar(name.to_string(), span));
                Ty::Error
            }
        }
    }

    /// Infer type of a binary operation.
    ///
    /// Generates appropriate constraints based on the operator and returns
    /// the result type.
    fn infer_binary(
        &mut self,
        lhs_id: ExprId,
        op: BinOp,
        rhs_id: ExprId,
        span: Span,
    ) -> Ty {
        let lhs_ty = self.infer_expr(lhs_id);
        let rhs_ty = self.infer_expr(rhs_id);

        match op {
            // Arithmetic: both numeric, result depends on operand types
            BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Mod | BinOp::Pow => {
                self.constrain(Constraint::Numeric(lhs_ty.clone(), span));
                self.constrain(Constraint::Numeric(rhs_ty.clone(), span));
                // If either is Float, result is Float; else fresh numeric
                if lhs_ty == Ty::Float || rhs_ty == Ty::Float {
                    Ty::Float
                } else if lhs_ty == Ty::Int && rhs_ty == Ty::Int {
                    Ty::Int
                } else {
                    // One or both are type vars; result is fresh numeric
                    let result = self.fresh();
                    self.constrain(Constraint::Numeric(result.clone(), span));
                    result
                }
            }

            // Division always returns Float
            BinOp::Div => {
                self.constrain(Constraint::Numeric(lhs_ty, span));
                self.constrain(Constraint::Numeric(rhs_ty, span));
                Ty::Float
            }

            // Floor division always returns Int
            BinOp::FloorDiv => {
                self.constrain(Constraint::Numeric(lhs_ty, span));
                self.constrain(Constraint::Numeric(rhs_ty, span));
                Ty::Int
            }

            // Comparison: operands must unify, result is Bool
            BinOp::Eq
            | BinOp::Ne
            | BinOp::Lt
            | BinOp::Gt
            | BinOp::Le
            | BinOp::Ge => {
                self.unify(lhs_ty, rhs_ty, span);
                Ty::Bool
            }

            // Logical: both must be Bool, result is Bool
            BinOp::And | BinOp::Or => {
                self.unify(lhs_ty, Ty::Bool, span);
                self.unify(rhs_ty, Ty::Bool, span);
                Ty::Bool
            }

            // String concatenation: lhs is String, rhs is Stringable
            BinOp::Concat => {
                self.unify(lhs_ty, Ty::String, span);
                self.constrain(Constraint::Stringable(rhs_ty, span));
                Ty::String
            }

            // Coalesce: lhs is Option[T] or Result[T, E], rhs unifies with T
            BinOp::Coalesce => {
                let inner = self.fresh();
                self.constrain(Constraint::Unwrappable {
                    ty: lhs_ty,
                    inner: inner.clone(),
                    span,
                });
                self.unify(rhs_ty, inner.clone(), span);
                inner
            }

            // Pipe: rhs is callable with lhs as argument
            BinOp::Pipe => {
                let result = self.fresh();
                self.constrain(Constraint::Callable {
                    callee: rhs_ty,
                    args: smallvec::smallvec![lhs_ty],
                    ret: result.clone(),
                    span,
                });
                result
            }
        }
    }

    /// Infer type of a unary operation.
    ///
    /// Generates appropriate constraints based on the operator and returns
    /// the result type.
    fn infer_unary(&mut self, op: UnOp, operand_id: ExprId, span: Span) -> Ty {
        let operand_ty = self.infer_expr(operand_id);

        match op {
            // Negation: operand must be numeric, result is same type
            UnOp::Neg => {
                self.constrain(Constraint::Numeric(operand_ty.clone(), span));
                operand_ty
            }

            // Logical not: operand must be Bool, result is Bool
            UnOp::Not => {
                self.unify(operand_ty, Ty::Bool, span);
                Ty::Bool
            }
        }
    }

    /// Infer type of an array literal.
    ///
    /// Empty arrays get a fresh element type. Non-empty arrays infer the first
    /// element's type and unify all subsequent elements with it.
    fn infer_array(&mut self, elems: &[ExprId], span: Span) -> Ty {
        if let Some((first, rest)) = elems.split_first() {
            let first_ty = self.infer_expr(*first);
            rest.iter().for_each(|id| {
                let ty = self.infer_expr(*id);
                self.unify(first_ty.clone(), ty, span);
            });
            Ty::Array(Box::new(first_ty))
        } else {
            Ty::Array(Box::new(self.fresh()))
        }
    }

    /// Infer type of a tuple literal.
    ///
    /// Infers each element independently; the tuple type contains all element
    /// types in order. Empty tuples are handled as `Unit` in `infer_expr_inner`.
    fn infer_tuple(&mut self, elems: &SmallVec<[ExprId; 4]>) -> Ty {
        Ty::Tuple(elems.iter().map(|id| self.infer_expr(*id)).collect())
    }

    /// Infer type of an object literal.
    ///
    /// Produces a structural object type with inferred field types.
    fn infer_object(&mut self, fields: &[(String, ExprId)]) -> Ty {
        let obj_fields = fields
            .iter()
            .map(|(name, expr_id)| {
                let field_ty = self.infer_expr(*expr_id);
                let field_id = self.env.intern(name);
                (field_id, field_ty)
            })
            .collect();
        Ty::Object(obj_fields)
    }

    /// Infer type of a map literal.
    ///
    /// Keys are unified to a common type; values are unified to a common type.
    /// Empty maps get fresh type variables for both.
    fn infer_map_lit(
        &mut self,
        entries: &SmallVec<[(ExprId, ExprId); 8]>,
        span: Span,
    ) -> Ty {
        if let Some(((first_k, first_v), rest)) = entries.split_first() {
            let k_ty = self.infer_expr(*first_k);
            let v_ty = self.infer_expr(*first_v);
            rest.iter().for_each(|(k, v)| {
                let k = self.infer_expr(*k);
                let v = self.infer_expr(*v);
                self.unify(k_ty.clone(), k, span);
                self.unify(v_ty.clone(), v, span);
            });
            Ty::Map(Box::new(k_ty), Box::new(v_ty))
        } else {
            Ty::Map(Box::new(self.fresh()), Box::new(self.fresh()))
        }
    }

    /// Infer type of field access: `base.field`.
    ///
    /// Works for structural objects (`Ty::Object`) and named struct types
    /// (`Ty::Named` with `TypeDef::Struct`). For type variables, we cannot
    /// yet infer the field type without row polymorphism, so we create a
    /// structural object constraint.
    fn infer_field(&mut self, base_id: ExprId, field: &str, span: Span) -> Ty {
        let base_ty = self.infer_expr(base_id);
        self.field_type(&base_ty, field, span)
    }

    /// Convert an AST type expression to a `Ty`.
    ///
    /// The `subst` map substitutes type parameter names with concrete types;
    /// used for generic struct field resolution.
    fn ast_type_to_ty(
        &mut self,
        id: AstTypeExprId,
        subst: &HashMap<StringId, Ty>,
    ) -> Ty {
        self.ast.get_type_expr(id).map_or(Ty::Error, |te| match te {
            AstTypeExpr::Named(name) => {
                let name_id = self.env.intern(name);
                // Check substitution first (for type params)
                subst
                    .get(&name_id)
                    .cloned()
                    .unwrap_or_else(|| self.named_type_to_ty(name))
            }
            AstTypeExpr::App(name, args) => {
                let arg_tys: Vec<_> = args
                    .iter()
                    .map(|a| self.ast_type_to_ty(*a, subst))
                    .collect();
                self.parameterized_type_to_ty(name, arg_tys)
            }
            AstTypeExpr::Fn(params, ret) => {
                let param_tys: Vec<_> = params
                    .iter()
                    .map(|p| self.ast_type_to_ty(*p, subst))
                    .collect();
                let ret_ty = self.ast_type_to_ty(*ret, subst);
                Ty::Fn(param_tys, Box::new(ret_ty))
            }
            AstTypeExpr::Tuple(elems) => {
                let elem_tys: Vec<_> = elems
                    .iter()
                    .map(|e| self.ast_type_to_ty(*e, subst))
                    .collect();
                Ty::Tuple(elem_tys)
            }
            AstTypeExpr::Union(members) => {
                if members.is_empty() {
                    let span =
                        self.ast.type_expr_span(id).unwrap_or(Span::new(0, 0));
                    self.error(TypeError::EmptyUnion(span));
                    Ty::Error
                } else {
                    let member_tys: Vec<_> = members
                        .iter()
                        .map(|m| self.ast_type_to_ty(*m, subst))
                        .collect();
                    Ty::Union(member_tys)
                }
            }
            AstTypeExpr::Object(fields) => {
                let field_tys = fields
                    .iter()
                    .map(|(name, ty_id)| {
                        let name_id = self.env.intern(name);
                        let ty = self.ast_type_to_ty(*ty_id, subst);
                        (name_id, ty)
                    })
                    .collect();
                Ty::Object(field_tys)
            }
        })
    }

    /// Convert a simple named type to `Ty`.
    fn named_type_to_ty(&self, name: &str) -> Ty {
        match name {
            "Bool" => Ty::Bool,
            "Int" => Ty::Int,
            "Float" => Ty::Float,
            "Char" => Ty::Char,
            "String" => Ty::String,
            "Unit" => Ty::Unit,
            "Time" => Ty::Time,
            "Range" => Ty::Range,
            "Json" => Ty::Json,
            _ => {
                // Look up in registry
                self.env
                    .lookup_str(name)
                    .and_then(|id| self.registry.lookup(id))
                    .map_or(Ty::Unknown, |ty_id| Ty::Named(ty_id, vec![]))
            }
        }
    }

    /// Convert a parameterized type to `Ty`.
    fn parameterized_type_to_ty(&self, name: &str, args: Vec<Ty>) -> Ty {
        match name {
            "Array" => args
                .into_iter()
                .next()
                .map_or(Ty::Error, |t| Ty::Array(Box::new(t))),
            "Option" => args
                .into_iter()
                .next()
                .map_or(Ty::Error, |t| Ty::Option(Box::new(t))),
            "Result" => {
                let mut it = args.into_iter();
                it.next().map_or(Ty::Error, |ok| {
                    it.next().map_or(Ty::Error, |err| {
                        Ty::Result(Box::new(ok), Box::new(err))
                    })
                })
            }
            "Map" => {
                let mut it = args.into_iter();
                it.next().map_or(Ty::Error, |k| {
                    it.next().map_or(Ty::Error, |v| {
                        Ty::Map(Box::new(k), Box::new(v))
                    })
                })
            }
            _ => {
                // User-defined parameterized type
                self.env
                    .lookup_str(name)
                    .and_then(|id| self.registry.lookup(id))
                    .map_or(Ty::Unknown, |ty_id| Ty::Named(ty_id, args))
            }
        }
    }

    /// Extract the type of a field from a type.
    ///
    /// Handles structural objects, named structs, and type variables.
    fn field_type(&mut self, base_ty: &Ty, field: &str, span: Span) -> Ty {
        match base_ty {
            // Structural object: look up field in IndexMap
            Ty::Object(fields) => {
                let field_id = self.env.intern(field);
                fields.get(&field_id).cloned().unwrap_or_else(|| {
                    self.error(TypeError::FieldNotFound {
                        ty: base_ty.clone(),
                        field: field.to_string(),
                        span,
                    });
                    Ty::Error
                })
            }

            // Named type: check if it's a struct and look up field
            Ty::Named(type_id, type_args) => {
                let field_id = self.env.intern(field);
                let def = self.registry.get_def(*type_id);
                match def {
                    Some(TypeDef::Struct {
                        type_params,
                        fields,
                        ..
                    }) => {
                        // Copy what we need before borrowing self mutably
                        let field_ty_id = fields.get(&field_id).copied();
                        let params: SmallVec<[_; 2]> = type_params.clone();
                        match field_ty_id {
                            Some(ty_id) => {
                                let subst: HashMap<_, _> = params
                                    .iter()
                                    .zip(type_args.iter())
                                    .map(|(p, a)| (*p, a.clone()))
                                    .collect();
                                self.ast_type_to_ty(ty_id, &subst)
                            }
                            None => {
                                self.error(TypeError::FieldNotFound {
                                    ty: base_ty.clone(),
                                    field: field.to_string(),
                                    span,
                                });
                                Ty::Error
                            }
                        }
                    }
                    Some(_) => {
                        self.error(TypeError::NotAnObject(
                            base_ty.clone(),
                            span,
                        ));
                        Ty::Error
                    }
                    None => {
                        self.error(TypeError::NotAnObject(
                            base_ty.clone(),
                            span,
                        ));
                        Ty::Error
                    }
                }
            }

            // Type variable: create a structural object constraint with the
            // required field. The constraint solver will ensure the variable
            // unifies with a type that has this field.
            Ty::Var(_) => {
                let field_ty = self.fresh();
                let field_id = self.env.intern(field);
                let obj_ty = Ty::Object(
                    std::iter::once((field_id, field_ty.clone())).collect(),
                );
                self.unify(base_ty.clone(), obj_ty, span);
                field_ty
            }

            // Error recovery: propagate error
            Ty::Error => Ty::Error,

            // Unknown: field access might succeed at runtime
            Ty::Unknown => self.fresh(),

            // All other types don't have fields
            _ => {
                self.error(TypeError::NotAnObject(base_ty.clone(), span));
                Ty::Error
            }
        }
    }

    /// Infer type of optional field access: `base?.field`.
    ///
    /// The base must be `Option[T]` where `T` has the field.
    /// Returns `Option[FieldType]`.
    fn infer_optional_field(
        &mut self,
        base_id: ExprId,
        field: &str,
        span: Span,
    ) -> Ty {
        let base_ty = self.infer_expr(base_id);

        match &base_ty {
            Ty::Option(inner) => {
                let field_ty = self.field_type(inner, field, span);
                Ty::Option(Box::new(field_ty))
            }

            Ty::Var(_) => {
                // Base is a type variable; create Option[?t] constraint
                // where ?t has the required field
                let inner = self.fresh();
                let field_ty = self.field_type(&inner, field, span);
                self.unify(base_ty, Ty::Option(Box::new(inner)), span);
                Ty::Option(Box::new(field_ty))
            }

            Ty::Error => Ty::Error,

            _ => {
                // Optional field access on non-Option type
                // This could also work on the bare type, returning
                // Option[FieldType], but we require Option for now
                let fresh = self.fresh();
                self.error(TypeError::Mismatch {
                    expected: Ty::Option(Box::new(fresh)),
                    got: base_ty,
                    span,
                });
                Ty::Error
            }
        }
    }

    /// Infer type of tuple index: `tuple.0`, `tuple.1`, etc.
    fn infer_tuple_index(
        &mut self,
        base_id: ExprId,
        idx: u32,
        span: Span,
    ) -> Ty {
        let base_ty = self.infer_expr(base_id);

        match &base_ty {
            Ty::Tuple(elems) => {
                elems.get(idx as usize).cloned().unwrap_or_else(|| {
                    self.error(TypeError::TupleIndexOutOfBounds {
                        idx,
                        len: elems.len(),
                        span,
                    });
                    Ty::Error
                })
            }

            Ty::Var(_) => {
                // Cannot infer tuple structure from index access alone;
                // the constraint solver would need tuple row polymorphism.
                // For now, return fresh var and hope it unifies later.
                self.fresh()
            }

            Ty::Error => Ty::Error,

            _ => {
                self.error(TypeError::NotATuple(base_ty, span));
                Ty::Error
            }
        }
    }

    /// Infer type of index access: `base[idx]`.
    ///
    /// Works for `Array[T]` (index must be `Int`, returns `T`) and
    /// `Map[K, V]` (index unifies with `K`, returns `V`).
    fn infer_index(
        &mut self,
        base_id: ExprId,
        idx_id: ExprId,
        span: Span,
    ) -> Ty {
        let base_ty = self.infer_expr(base_id);
        let idx_ty = self.infer_expr(idx_id);

        match &base_ty {
            Ty::Array(elem) => {
                self.unify(idx_ty, Ty::Int, span);
                elem.as_ref().clone()
            }

            Ty::Map(key, val) => {
                self.unify(idx_ty, key.as_ref().clone(), span);
                val.as_ref().clone()
            }

            Ty::Var(_) => {
                // Base is type variable; could be Array or Map.
                // We can't know which, so return fresh and let unification handle it.
                self.fresh()
            }

            Ty::Error => Ty::Error,

            Ty::String => {
                // String indexing returns Char
                self.unify(idx_ty, Ty::Int, span);
                Ty::Char
            }

            _ => {
                self.error(TypeError::NotIndexable(base_ty, span));
                Ty::Error
            }
        }
    }

    /// Infer type of JSON access operators.
    ///
    /// | Operator | Returns                           |
    /// |----------|-----------------------------------|
    /// | `.`      | `Json`                            |
    /// | `..`     | `Option[Scalar]` (union)          |
    /// | `->`     | `Json`                            |
    /// | `->>`    | `Option[Scalar]` (union)          |
    fn infer_json_access(
        &mut self,
        base_id: ExprId,
        kind: &JsonAccessKind,
        key: &JsonAccessKey,
        span: Span,
    ) -> Ty {
        let base_ty = self.infer_expr(base_id);

        // Infer the key expression type if dynamic
        if let JsonAccessKey::Expr(key_id) = key {
            let key_ty = self.infer_expr(*key_id);
            // Dynamic key must be String
            self.unify(key_ty, Ty::String, span);
        }

        // Base must be Json
        match &base_ty {
            Ty::Json => match kind {
                JsonAccessKind::Json => Ty::Json,
                JsonAccessKind::Scalar => {
                    Ty::Option(Box::new(Ty::Named(TypeId::SCALAR, vec![])))
                }
            },

            Ty::Var(_) => {
                // Constrain base to be Json
                self.unify(base_ty, Ty::Json, span);
                match kind {
                    JsonAccessKind::Json => Ty::Json,
                    JsonAccessKind::Scalar => {
                        Ty::Option(Box::new(Ty::Named(TypeId::SCALAR, vec![])))
                    }
                }
            }

            Ty::Error => Ty::Error,

            _ => {
                self.error(TypeError::NotJson(base_ty, span));
                Ty::Error
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test helper: create minimal context components for testing.
    ///
    /// Returns context state without needing full `InferCtx` construction,
    /// since `TypeRegistry::new` requires mutable arenas.
    struct TestState {
        env: TypeEnv,
        constraints: Vec<Constraint>,
        next_var: u32,
        expr_types: HashMap<ExprId, Ty>,
        errors: Vec<TypeError>,
    }

    impl TestState {
        fn new() -> Self {
            Self {
                env: TypeEnv::new(),
                constraints: Vec::new(),
                next_var: 0,
                expr_types: HashMap::new(),
                errors: Vec::new(),
            }
        }

        fn with_next_var(mut self, n: u32) -> Self {
            self.next_var = n;
            self
        }

        fn fresh_var(&mut self) -> TyVar {
            let v = TyVar::new(self.next_var);
            self.next_var += 1;
            v
        }

        fn fresh(&mut self) -> Ty {
            Ty::Var(self.fresh_var())
        }

        fn constrain(&mut self, c: Constraint) {
            self.constraints.push(c);
        }

        fn unify(&mut self, t1: Ty, t2: Ty, span: Span) {
            self.constrain(Constraint::Eq(t1, t2, span));
        }

        fn error(&mut self, e: TypeError) {
            self.errors.push(e);
        }

        fn has_errors(&self) -> bool {
            !self.errors.is_empty()
        }
    }

    #[test]
    fn fresh_var_increments() {
        let mut state = TestState::new();

        let v0 = state.fresh_var();
        let v1 = state.fresh_var();
        let v2 = state.fresh_var();

        assert_eq!(v0, TyVar::new(0));
        assert_eq!(v1, TyVar::new(1));
        assert_eq!(v2, TyVar::new(2));
        assert_eq!(state.next_var, 3);
    }

    #[test]
    fn fresh_returns_ty_var() {
        let mut state = TestState::new().with_next_var(10);

        let ty = state.fresh();
        assert_eq!(ty, Ty::Var(TyVar::new(10)));
    }

    #[test]
    fn constrain_collects() {
        let mut state = TestState::new();

        let span = Span::new(0, 5);
        state.constrain(Constraint::Numeric(Ty::Int, span));
        state.constrain(Constraint::Eq(Ty::Int, Ty::Float, span));

        assert_eq!(state.constraints.len(), 2);
    }

    #[test]
    fn unify_adds_eq_constraint() {
        let mut state = TestState::new();

        let span = Span::new(0, 5);
        state.unify(Ty::Int, Ty::String, span);

        assert_eq!(state.constraints.len(), 1);
        match &state.constraints[0] {
            Constraint::Eq(t1, t2, s) => {
                assert_eq!(*t1, Ty::Int);
                assert_eq!(*t2, Ty::String);
                assert_eq!(*s, span);
            }
            _ => panic!("expected Eq constraint"),
        }
    }

    #[test]
    fn error_collects() {
        let mut state = TestState::new();

        assert!(!state.has_errors());

        let span = Span::new(0, 5);
        state.error(TypeError::UndefinedVar("x".to_string(), span));

        assert!(state.has_errors());
        assert_eq!(state.errors.len(), 1);
    }

    #[test]
    fn constraint_span() {
        let span = Span::new(10, 20);

        assert_eq!(Constraint::Eq(Ty::Int, Ty::Int, span).span(), span);
        assert_eq!(Constraint::Numeric(Ty::Int, span).span(), span);
        assert_eq!(
            Constraint::Callable {
                callee: Ty::Int,
                args: SmallVec::new(),
                ret: Ty::Int,
                span
            }
            .span(),
            span
        );
        assert_eq!(Constraint::Stringable(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Jsonable(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Subscript(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Storable(Ty::Int, span).span(), span);
        assert_eq!(
            Constraint::Unwrappable {
                ty: Ty::Int,
                inner: Ty::Int,
                span
            }
            .span(),
            span
        );
    }

    use crate::typecheck::Scheme;
    use crate::value::{TypeExprArena, ValueArena};

    /// Create an `InferCtx` for testing with a minimal AST.
    fn test_ctx(ast: &Ast) -> InferCtx<'_> {
        let mut arena = ValueArena::new();
        let mut type_exprs = TypeExprArena::new();
        let registry = TypeRegistry::new(&mut arena, &mut type_exprs).unwrap();
        // Leak to get 'static lifetime; tests don't need to clean up
        let registry = Box::leak(Box::new(registry));
        InferCtx::new(ast, registry)
    }

    /// Create an AST with a single expression.
    fn ast_with_expr(expr: Expr) -> (Ast, ExprId) {
        let mut ast = Ast::new();
        let id = ast.add_expr(expr, Span::new(0, 10)).unwrap();
        (ast, id)
    }

    #[test]
    fn infer_literal_bool_true() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Bool(true)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_literal_bool_false() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Bool(false)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_literal_int() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Int(42)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_literal_float() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Float(3.14)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_literal_char() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Char('x')));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Char);
    }

    #[test]
    fn infer_literal_string() {
        let (ast, id) =
            ast_with_expr(Expr::Literal(Literal::String("hello".into())));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
    }

    #[test]
    fn infer_literal_null() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Null));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Json);
    }

    #[test]
    fn infer_literal_unit() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Unit));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Unit);
    }

    #[test]
    fn infer_empty_tuple_as_unit() {
        let (ast, id) = ast_with_expr(Expr::Tuple(smallvec::smallvec![]));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Unit);
    }

    #[test]
    fn infer_var_found() {
        let (ast, id) = ast_with_expr(Expr::Var("x".into()));
        let mut ctx = test_ctx(&ast);
        // Bind "x" to Int in the environment
        ctx.env_mut().bind("x", Scheme::mono(Ty::Int));
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_var_not_found() {
        let (ast, id) = ast_with_expr(Expr::Var("undefined".into()));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        assert_eq!(ctx.errors().len(), 1);
        match &ctx.errors()[0] {
            TypeError::UndefinedVar(name, _) => assert_eq!(name, "undefined"),
            e => panic!("expected UndefinedVar, got {e:?}"),
        }
    }

    #[test]
    fn infer_var_instantiates_scheme() {
        let (ast, id) = ast_with_expr(Expr::Var("id".into()));
        let mut ctx = test_ctx(&ast);
        // Bind "id" to a polymorphic scheme: forall a. a -> a
        // Use a high index to avoid collision with fresh vars (which start at 0)
        let a = TyVar::new(1000);
        let scheme = Scheme {
            vars: vec![a],
            ty: Ty::Fn(vec![Ty::Var(a)], Box::new(Ty::Var(a))),
        };
        ctx.env_mut().bind("id", scheme);
        let ty = ctx.infer_expr(id);
        // Should get Fn with fresh type variable (not the original `a`)
        match ty {
            Ty::Fn(params, ret) => {
                assert_eq!(params.len(), 1);
                // The fresh variable should have a different index
                match (&params[0], ret.as_ref()) {
                    (Ty::Var(v1), Ty::Var(v2)) => {
                        assert_eq!(v1, v2); // Same fresh variable
                        assert_ne!(*v1, a); // Different from original (1000)
                    }
                    _ => panic!("expected Var types"),
                }
            }
            _ => panic!("expected Fn type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_expr_records_type() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Int(42)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ctx.get_type(id), Some(&ty));
    }

    /// Helper to create AST with binary expression from two literals.
    fn ast_with_binary(lhs: Literal, op: BinOp, rhs: Literal) -> (Ast, ExprId) {
        let mut ast = Ast::new();
        let l = ast.add_expr(Expr::Literal(lhs), Span::new(0, 1)).unwrap();
        let r = ast.add_expr(Expr::Literal(rhs), Span::new(4, 5)).unwrap();
        let bin = ast
            .add_expr(Expr::Binary(l, op, r), Span::new(0, 5))
            .unwrap();
        (ast, bin)
    }

    // Arithmetic operators

    #[test]
    fn infer_add_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Add, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
        // Should have 2 Numeric constraints for operands
        let numerics: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Numeric(_, _)))
            .collect();
        assert_eq!(numerics.len(), 2);
    }

    #[test]
    fn infer_add_float_float() {
        let (ast, id) = ast_with_binary(
            Literal::Float(1.0),
            BinOp::Add,
            Literal::Float(2.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_add_int_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Add, Literal::Float(2.0));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float); // Widening to Float
    }

    #[test]
    fn infer_add_float_int() {
        let (ast, id) =
            ast_with_binary(Literal::Float(1.0), BinOp::Add, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_sub_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Sub, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_mul_int_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(2), BinOp::Mul, Literal::Float(3.5));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_mod_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::Mod, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_pow_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(2), BinOp::Pow, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_pow_float_int() {
        let (ast, id) =
            ast_with_binary(Literal::Float(2.0), BinOp::Pow, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    // Division operators

    #[test]
    fn infer_div_int_int_returns_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::Div, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float); // Division always Float
    }

    #[test]
    fn infer_floor_div_int_int_returns_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::FloorDiv, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int); // Floor division always Int
    }

    #[test]
    fn infer_floor_div_float_float_returns_int() {
        let (ast, id) = ast_with_binary(
            Literal::Float(10.0),
            BinOp::FloorDiv,
            Literal::Float(3.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int); // Floor division always Int
    }

    // Comparison operators

    #[test]
    fn infer_eq_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Eq, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
        // Should have Eq constraint unifying operands
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(_, _, _))));
    }

    #[test]
    fn infer_ne_returns_bool() {
        let (ast, id) = ast_with_binary(
            Literal::String("a".into()),
            BinOp::Ne,
            Literal::String("b".into()),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_lt_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Lt, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_gt_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Gt, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_le_returns_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Float(1.0),
            BinOp::Le,
            Literal::Float(2.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_ge_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Ge, Literal::Int(5));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    // Logical operators

    #[test]
    fn infer_and_bool_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Bool(true),
            BinOp::And,
            Literal::Bool(false),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
        // Should have 2 Eq constraints unifying operands with Bool
        let eqs: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Eq(_, Ty::Bool, _)))
            .collect();
        assert_eq!(eqs.len(), 2);
    }

    #[test]
    fn infer_or_bool_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Bool(false),
            BinOp::Or,
            Literal::Bool(true),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    // String concatenation

    #[test]
    fn infer_concat_string_string() {
        let (ast, id) = ast_with_binary(
            Literal::String("hello".into()),
            BinOp::Concat,
            Literal::String(" world".into()),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
        // Should have Stringable constraint for rhs
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Stringable(_, _))));
    }

    #[test]
    fn infer_concat_string_int() {
        // String ++ Int is valid; Int is Stringable
        let (ast, id) = ast_with_binary(
            Literal::String("count: ".into()),
            BinOp::Concat,
            Literal::Int(42),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
        // Stringable constraint on Int
        let stringables: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Stringable(Ty::Int, _)))
            .collect();
        assert_eq!(stringables.len(), 1);
    }

    // Coalesce

    #[test]
    fn infer_coalesce_creates_unwrappable_constraint() {
        // For coalesce, lhs needs to be Option[T] or Result[T, E]
        // Here we test with a variable that would be Option[Int]
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Var("opt".into()), Span::new(0, 3))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(7, 8))
            .unwrap();
        let coal = ast
            .add_expr(Expr::Binary(lhs, BinOp::Coalesce, rhs), Span::new(0, 8))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "opt" to Option[Int]
        ctx.env_mut()
            .bind("opt", Scheme::mono(Ty::Option(Box::new(Ty::Int))));
        let ty = ctx.infer_expr(coal);

        // Result should be fresh var unified with rhs (Int)
        match ty {
            Ty::Var(_) => {
                // Should have Unwrappable constraint
                assert!(ctx
                    .constraints()
                    .iter()
                    .any(|c| matches!(c, Constraint::Unwrappable { .. })));
                // And Eq constraint unifying inner with rhs
                assert!(ctx
                    .constraints()
                    .iter()
                    .any(|c| matches!(c, Constraint::Eq(_, _, _))));
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    // Pipe

    #[test]
    fn infer_pipe_creates_callable_constraint() {
        // 42 |> f should add Callable constraint on f
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(0, 2))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Var("f".into()), Span::new(6, 7))
            .unwrap();
        let pipe = ast
            .add_expr(Expr::Binary(lhs, BinOp::Pipe, rhs), Span::new(0, 7))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "f" to Int -> String
        ctx.env_mut().bind(
            "f",
            Scheme::mono(Ty::Fn(vec![Ty::Int], Box::new(Ty::String))),
        );
        let ty = ctx.infer_expr(pipe);

        // Result is fresh var
        match ty {
            Ty::Var(_) => {
                // Should have Callable constraint
                let callables: Vec<_> = ctx
                    .constraints()
                    .iter()
                    .filter(|c| matches!(c, Constraint::Callable { .. }))
                    .collect();
                assert_eq!(callables.len(), 1);
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    // Unary operators

    #[test]
    fn infer_neg_int() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(1, 3))
            .unwrap();
        let neg = ast
            .add_expr(Expr::Unary(UnOp::Neg, operand), Span::new(0, 3))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(neg);
        assert_eq!(ty, Ty::Int);
        // Should have Numeric constraint
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Numeric(Ty::Int, _))));
    }

    #[test]
    fn infer_neg_float() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Float(3.14)), Span::new(1, 5))
            .unwrap();
        let neg = ast
            .add_expr(Expr::Unary(UnOp::Neg, operand), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(neg);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_not_bool() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Bool(true)), Span::new(1, 5))
            .unwrap();
        let not = ast
            .add_expr(Expr::Unary(UnOp::Not, operand), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(not);
        assert_eq!(ty, Ty::Bool);
        // Should have Eq constraint unifying operand with Bool
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::Bool, Ty::Bool, _))));
    }

    // Range

    #[test]
    fn infer_range_int_int() {
        let mut ast = Ast::new();
        let start = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(0, 1))
            .unwrap();
        let end = ast
            .add_expr(Expr::Literal(Literal::Int(10)), Span::new(4, 6))
            .unwrap();
        let range = ast
            .add_expr(Expr::Range(start, end, false), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(range);
        assert_eq!(ty, Ty::Range);
        // Should have 2 Eq constraints unifying operands with Int
        let int_constraints: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Eq(Ty::Int, Ty::Int, _)))
            .collect();
        assert_eq!(int_constraints.len(), 2);
    }

    #[test]
    fn infer_range_inclusive_int_int() {
        let mut ast = Ast::new();
        let start = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(0, 1))
            .unwrap();
        let end = ast
            .add_expr(Expr::Literal(Literal::Int(5)), Span::new(5, 6))
            .unwrap();
        let range = ast
            .add_expr(Expr::Range(start, end, true), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(range);
        assert_eq!(ty, Ty::Range); // Same type regardless of inclusive flag
    }

    // Arithmetic with type variables

    #[test]
    fn infer_add_with_var_produces_fresh_numeric() {
        // x + 1 where x is a type variable
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Var("x".into()), Span::new(0, 1))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(4, 5))
            .unwrap();
        let add = ast
            .add_expr(Expr::Binary(lhs, BinOp::Add, rhs), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "x" to a fresh type variable via polymorphic scheme
        let a = TyVar::new(1000);
        ctx.env_mut().bind(
            "x",
            Scheme {
                vars: vec![a],
                ty: Ty::Var(a),
            },
        );

        let ty = ctx.infer_expr(add);
        // Result should be a fresh type variable (since one operand is var)
        match ty {
            Ty::Var(_) => {
                // Should have 3 Numeric constraints: lhs, rhs, result
                let numerics: Vec<_> = ctx
                    .constraints()
                    .iter()
                    .filter(|c| matches!(c, Constraint::Numeric(_, _)))
                    .collect();
                assert_eq!(numerics.len(), 3);
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    #[test]
    fn infer_array_empty() {
        let (ast, id) = ast_with_expr(Expr::Array(vec![]));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        match ty {
            Ty::Array(elem) => match *elem {
                Ty::Var(_) => {} // Fresh type variable is expected
                _ => panic!("expected type variable for empty array element"),
            },
            _ => panic!("expected Array type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_array_homogeneous_int() {
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(Expr::Literal(Literal::Int(2)), Span::new(4, 5))
            .unwrap();
        let e3 = ast
            .add_expr(Expr::Literal(Literal::Int(3)), Span::new(7, 8))
            .unwrap();
        let arr = ast
            .add_expr(Expr::Array(vec![e1, e2, e3]), Span::new(0, 9))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(arr);
        assert_eq!(ty, Ty::Array(Box::new(Ty::Int)));
    }

    #[test]
    fn infer_array_homogeneous_string() {
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(
                Expr::Literal(Literal::String("a".into())),
                Span::new(1, 4),
            )
            .unwrap();
        let e2 = ast
            .add_expr(
                Expr::Literal(Literal::String("b".into())),
                Span::new(6, 9),
            )
            .unwrap();
        let arr = ast
            .add_expr(Expr::Array(vec![e1, e2]), Span::new(0, 10))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(arr);
        assert_eq!(ty, Ty::Array(Box::new(Ty::String)));
    }

    #[test]
    fn infer_array_single_element() {
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Bool(true)), Span::new(1, 5))
            .unwrap();
        let arr = ast
            .add_expr(Expr::Array(vec![e1]), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(arr);
        assert_eq!(ty, Ty::Array(Box::new(Ty::Bool)));
    }

    #[test]
    fn infer_array_mixed_adds_constraints() {
        // [1, 2.0] should unify Int with Float
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(Expr::Literal(Literal::Float(2.0)), Span::new(4, 7))
            .unwrap();
        let arr = ast
            .add_expr(Expr::Array(vec![e1, e2]), Span::new(0, 8))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(arr);
        // Result type is Array[Int] (first element's type)
        // but there's an Eq constraint to unify Int with Float
        assert_eq!(ty, Ty::Array(Box::new(Ty::Int)));
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::Int, Ty::Float, _))));
    }

    // Tuples

    #[test]
    fn infer_tuple_two_elements() {
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(4, 11),
            )
            .unwrap();
        let tup = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![e1, e2]),
                Span::new(0, 12),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(tup);
        assert_eq!(ty, Ty::Tuple(vec![Ty::Int, Ty::String]));
    }

    #[test]
    fn infer_tuple_three_elements() {
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Bool(true)), Span::new(1, 5))
            .unwrap();
        let e2 = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(7, 9))
            .unwrap();
        let e3 = ast
            .add_expr(Expr::Literal(Literal::Float(3.14)), Span::new(11, 15))
            .unwrap();
        let tup = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![e1, e2, e3]),
                Span::new(0, 16),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(tup);
        assert_eq!(ty, Ty::Tuple(vec![Ty::Bool, Ty::Int, Ty::Float]));
    }

    #[test]
    fn infer_tuple_single_element() {
        // Single-element tuple (trailing comma): (42,)
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(1, 3))
            .unwrap();
        let tup = ast
            .add_expr(Expr::Tuple(smallvec::smallvec![e1]), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(tup);
        assert_eq!(ty, Ty::Tuple(vec![Ty::Int]));
    }

    #[test]
    fn infer_tuple_nested() {
        // ((1, 2), "hello")
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(2, 3))
            .unwrap();
        let e2 = ast
            .add_expr(Expr::Literal(Literal::Int(2)), Span::new(5, 6))
            .unwrap();
        let inner = ast
            .add_expr(Expr::Tuple(smallvec::smallvec![e1, e2]), Span::new(1, 7))
            .unwrap();
        let e3 = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(9, 16),
            )
            .unwrap();
        let outer = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![inner, e3]),
                Span::new(0, 17),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(outer);
        assert_eq!(
            ty,
            Ty::Tuple(vec![Ty::Tuple(vec![Ty::Int, Ty::Int]), Ty::String])
        );
    }

    // Objects

    #[test]
    fn infer_object_single_field() {
        let mut ast = Ast::new();
        let val = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(7, 9))
            .unwrap();
        let obj = ast
            .add_expr(Expr::Object(vec![("age".into(), val)]), Span::new(0, 11))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(obj);
        match ty {
            Ty::Object(fields) => {
                assert_eq!(fields.len(), 1);
                // Look up by getting the field value
                let field_ty = fields.values().next().unwrap();
                assert_eq!(*field_ty, Ty::Int);
            }
            _ => panic!("expected Object type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_object_multiple_fields() {
        let mut ast = Ast::new();
        let v1 = ast
            .add_expr(
                Expr::Literal(Literal::String("Alice".into())),
                Span::new(8, 15),
            )
            .unwrap();
        let v2 = ast
            .add_expr(Expr::Literal(Literal::Int(30)), Span::new(23, 25))
            .unwrap();
        let obj = ast
            .add_expr(
                Expr::Object(vec![("name".into(), v1), ("age".into(), v2)]),
                Span::new(0, 27),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(obj);
        match ty {
            Ty::Object(fields) => {
                assert_eq!(fields.len(), 2);
                let tys: Vec<_> = fields.values().collect();
                assert_eq!(*tys[0], Ty::String);
                assert_eq!(*tys[1], Ty::Int);
            }
            _ => panic!("expected Object type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_object_nested() {
        // { outer: { inner: 123 } }
        let mut ast = Ast::new();
        let inner_val = ast
            .add_expr(Expr::Literal(Literal::Int(123)), Span::new(18, 21))
            .unwrap();
        let inner_obj = ast
            .add_expr(
                Expr::Object(vec![("inner".into(), inner_val)]),
                Span::new(9, 23),
            )
            .unwrap();
        let outer = ast
            .add_expr(
                Expr::Object(vec![("outer".into(), inner_obj)]),
                Span::new(0, 25),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(outer);
        match ty {
            Ty::Object(fields) => {
                assert_eq!(fields.len(), 1);
                let outer_ty = fields.values().next().unwrap();
                match outer_ty {
                    Ty::Object(inner_fields) => {
                        assert_eq!(inner_fields.len(), 1);
                        let inner_ty = inner_fields.values().next().unwrap();
                        assert_eq!(*inner_ty, Ty::Int);
                    }
                    _ => panic!("expected nested Object type"),
                }
            }
            _ => panic!("expected Object type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_object_empty() {
        let (ast, id) = ast_with_expr(Expr::Object(vec![]));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        match ty {
            Ty::Object(fields) => assert!(fields.is_empty()),
            _ => panic!("expected Object type, got {ty:?}"),
        }
    }

    // Map literals

    #[test]
    fn infer_map_empty() {
        let (ast, id) = ast_with_expr(Expr::MapLit(smallvec::smallvec![]));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        match ty {
            Ty::Map(k, v) => match (*k, *v) {
                (Ty::Var(_), Ty::Var(_)) => {}
                _ => panic!("expected type variables for empty map"),
            },
            _ => panic!("expected Map type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_map_single_entry() {
        let mut ast = Ast::new();
        let k = ast
            .add_expr(
                Expr::Literal(Literal::String("key".into())),
                Span::new(2, 7),
            )
            .unwrap();
        let v = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(11, 13))
            .unwrap();
        let map = ast
            .add_expr(
                Expr::MapLit(smallvec::smallvec![(k, v)]),
                Span::new(0, 15),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(map);
        assert_eq!(ty, Ty::Map(Box::new(Ty::String), Box::new(Ty::Int)));
    }

    #[test]
    fn infer_map_multiple_entries() {
        let mut ast = Ast::new();
        let k1 = ast
            .add_expr(
                Expr::Literal(Literal::String("a".into())),
                Span::new(2, 5),
            )
            .unwrap();
        let v1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(9, 10))
            .unwrap();
        let k2 = ast
            .add_expr(
                Expr::Literal(Literal::String("b".into())),
                Span::new(13, 16),
            )
            .unwrap();
        let v2 = ast
            .add_expr(Expr::Literal(Literal::Int(2)), Span::new(20, 21))
            .unwrap();
        let map = ast
            .add_expr(
                Expr::MapLit(smallvec::smallvec![(k1, v1), (k2, v2)]),
                Span::new(0, 23),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(map);
        assert_eq!(ty, Ty::Map(Box::new(Ty::String), Box::new(Ty::Int)));
        // Should have Eq constraints unifying keys and values
        let eq_constraints: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Eq(_, _, _)))
            .collect();
        // 2 constraints: one for keys (String ~ String), one for values (Int ~ Int)
        assert_eq!(eq_constraints.len(), 2);
    }

    #[test]
    fn infer_map_mixed_values_adds_constraints() {
        // { "a" => 1, "b" => 2.0 } should unify Int with Float
        let mut ast = Ast::new();
        let k1 = ast
            .add_expr(
                Expr::Literal(Literal::String("a".into())),
                Span::new(2, 5),
            )
            .unwrap();
        let v1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(9, 10))
            .unwrap();
        let k2 = ast
            .add_expr(
                Expr::Literal(Literal::String("b".into())),
                Span::new(13, 16),
            )
            .unwrap();
        let v2 = ast
            .add_expr(Expr::Literal(Literal::Float(2.0)), Span::new(20, 23))
            .unwrap();
        let map = ast
            .add_expr(
                Expr::MapLit(smallvec::smallvec![(k1, v1), (k2, v2)]),
                Span::new(0, 25),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(map);
        // Result type is Map[String, Int] (first entry's types)
        assert_eq!(ty, Ty::Map(Box::new(Ty::String), Box::new(Ty::Int)));
        // but there's an Eq constraint to unify Int with Float
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::Int, Ty::Float, _))));
    }

    #[test]
    fn infer_map_int_keys() {
        let mut ast = Ast::new();
        let k1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(2, 3))
            .unwrap();
        let v1 = ast
            .add_expr(
                Expr::Literal(Literal::String("one".into())),
                Span::new(7, 12),
            )
            .unwrap();
        let k2 = ast
            .add_expr(Expr::Literal(Literal::Int(2)), Span::new(15, 16))
            .unwrap();
        let v2 = ast
            .add_expr(
                Expr::Literal(Literal::String("two".into())),
                Span::new(20, 25),
            )
            .unwrap();
        let map = ast
            .add_expr(
                Expr::MapLit(smallvec::smallvec![(k1, v1), (k2, v2)]),
                Span::new(0, 27),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(map);
        assert_eq!(ty, Ty::Map(Box::new(Ty::Int), Box::new(Ty::String)));
    }

    // Field access

    #[test]
    fn infer_field_access_object() {
        // { name: "Alice" }.name
        let mut ast = Ast::new();
        let val = ast
            .add_expr(
                Expr::Literal(Literal::String("Alice".into())),
                Span::new(8, 15),
            )
            .unwrap();
        let obj = ast
            .add_expr(
                Expr::Object(vec![("name".into(), val)]),
                Span::new(0, 17),
            )
            .unwrap();
        let field = ast
            .add_expr(Expr::Field(obj, "name".into()), Span::new(0, 22))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(field);
        assert_eq!(ty, Ty::String);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_field_access_object_nested() {
        // { user: { name: "Alice" } }.user.name
        let mut ast = Ast::new();
        let name_val = ast
            .add_expr(
                Expr::Literal(Literal::String("Alice".into())),
                Span::new(16, 23),
            )
            .unwrap();
        let inner_obj = ast
            .add_expr(
                Expr::Object(vec![("name".into(), name_val)]),
                Span::new(8, 25),
            )
            .unwrap();
        let outer_obj = ast
            .add_expr(
                Expr::Object(vec![("user".into(), inner_obj)]),
                Span::new(0, 27),
            )
            .unwrap();
        let user_field = ast
            .add_expr(Expr::Field(outer_obj, "user".into()), Span::new(0, 32))
            .unwrap();
        let name_field = ast
            .add_expr(Expr::Field(user_field, "name".into()), Span::new(0, 37))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(name_field);
        assert_eq!(ty, Ty::String);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_field_access_missing_field() {
        // { name: "Alice" }.age
        let mut ast = Ast::new();
        let val = ast
            .add_expr(
                Expr::Literal(Literal::String("Alice".into())),
                Span::new(8, 15),
            )
            .unwrap();
        let obj = ast
            .add_expr(
                Expr::Object(vec![("name".into(), val)]),
                Span::new(0, 17),
            )
            .unwrap();
        let field = ast
            .add_expr(Expr::Field(obj, "age".into()), Span::new(0, 21))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(field);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::FieldNotFound { field, .. } => {
                assert_eq!(field, "age");
            }
            e => panic!("expected FieldNotFound, got {e:?}"),
        }
    }

    #[test]
    fn infer_field_access_on_int() {
        // 42.field
        let mut ast = Ast::new();
        let n = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(0, 2))
            .unwrap();
        let field = ast
            .add_expr(Expr::Field(n, "field".into()), Span::new(0, 8))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(field);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::NotAnObject(_, _) => {}
            e => panic!("expected NotAnObject, got {e:?}"),
        }
    }

    #[test]
    fn infer_field_access_var_creates_constraint() {
        // x.name where x is a type variable
        let mut ast = Ast::new();
        let var = ast
            .add_expr(Expr::Var("x".into()), Span::new(0, 1))
            .unwrap();
        let field = ast
            .add_expr(Expr::Field(var, "name".into()), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind x to fresh type variable
        let a = TyVar::new(1000);
        ctx.env_mut().bind(
            "x",
            Scheme {
                vars: vec![a],
                ty: Ty::Var(a),
            },
        );
        let ty = ctx.infer_expr(field);
        // Result should be a fresh type variable
        match ty {
            Ty::Var(_) => {
                // Should have Eq constraint with structural object
                assert!(ctx.constraints().iter().any(|c| matches!(
                    c,
                    Constraint::Eq(Ty::Var(_), Ty::Object(_), _)
                )));
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    // Tuple indexing

    #[test]
    fn infer_tuple_index_first() {
        // (1, "hello").0
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(4, 11),
            )
            .unwrap();
        let tup = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![e1, e2]),
                Span::new(0, 12),
            )
            .unwrap();
        let idx = ast
            .add_expr(Expr::TupleIndex(tup, 0), Span::new(0, 14))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Int);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_tuple_index_second() {
        // (1, "hello").1
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(4, 11),
            )
            .unwrap();
        let tup = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![e1, e2]),
                Span::new(0, 12),
            )
            .unwrap();
        let idx = ast
            .add_expr(Expr::TupleIndex(tup, 1), Span::new(0, 14))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::String);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_tuple_index_out_of_bounds() {
        // (1, "hello").5
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(4, 11),
            )
            .unwrap();
        let tup = ast
            .add_expr(
                Expr::Tuple(smallvec::smallvec![e1, e2]),
                Span::new(0, 12),
            )
            .unwrap();
        let idx = ast
            .add_expr(Expr::TupleIndex(tup, 5), Span::new(0, 14))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::TupleIndexOutOfBounds { idx, len, .. } => {
                assert_eq!(*idx, 5);
                assert_eq!(*len, 2);
            }
            e => panic!("expected TupleIndexOutOfBounds, got {e:?}"),
        }
    }

    #[test]
    fn infer_tuple_index_on_non_tuple() {
        // "hello".0
        let mut ast = Ast::new();
        let s = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(0, 7),
            )
            .unwrap();
        let idx = ast
            .add_expr(Expr::TupleIndex(s, 0), Span::new(0, 9))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::NotATuple(_, _) => {}
            e => panic!("expected NotATuple, got {e:?}"),
        }
    }

    // Index access

    #[test]
    fn infer_index_array() {
        // [1, 2, 3][0]
        let mut ast = Ast::new();
        let e1 = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(1, 2))
            .unwrap();
        let e2 = ast
            .add_expr(Expr::Literal(Literal::Int(2)), Span::new(4, 5))
            .unwrap();
        let e3 = ast
            .add_expr(Expr::Literal(Literal::Int(3)), Span::new(7, 8))
            .unwrap();
        let arr = ast
            .add_expr(Expr::Array(vec![e1, e2, e3]), Span::new(0, 9))
            .unwrap();
        let idx_val = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(10, 11))
            .unwrap();
        let idx = ast
            .add_expr(Expr::Index(arr, idx_val), Span::new(0, 12))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Int);
        // Index should be unified with Int
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::Int, Ty::Int, _))));
    }

    #[test]
    fn infer_index_map() {
        // { "a" => 1 }["a"]
        let mut ast = Ast::new();
        let k = ast
            .add_expr(
                Expr::Literal(Literal::String("a".into())),
                Span::new(2, 5),
            )
            .unwrap();
        let v = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(9, 10))
            .unwrap();
        let map = ast
            .add_expr(
                Expr::MapLit(smallvec::smallvec![(k, v)]),
                Span::new(0, 12),
            )
            .unwrap();
        let idx_val = ast
            .add_expr(
                Expr::Literal(Literal::String("a".into())),
                Span::new(13, 16),
            )
            .unwrap();
        let idx = ast
            .add_expr(Expr::Index(map, idx_val), Span::new(0, 17))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_index_string() {
        // "hello"[0]
        let mut ast = Ast::new();
        let s = ast
            .add_expr(
                Expr::Literal(Literal::String("hello".into())),
                Span::new(0, 7),
            )
            .unwrap();
        let idx_val = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(8, 9))
            .unwrap();
        let idx = ast
            .add_expr(Expr::Index(s, idx_val), Span::new(0, 10))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Char);
    }

    #[test]
    fn infer_index_on_non_indexable() {
        // true[0]
        let mut ast = Ast::new();
        let b = ast
            .add_expr(Expr::Literal(Literal::Bool(true)), Span::new(0, 4))
            .unwrap();
        let idx_val = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(5, 6))
            .unwrap();
        let idx = ast
            .add_expr(Expr::Index(b, idx_val), Span::new(0, 7))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(idx);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::NotIndexable(_, _) => {}
            e => panic!("expected NotIndexable, got {e:?}"),
        }
    }

    // JSON access

    #[test]
    fn infer_json_access_field() {
        // data.name (where data is Json)
        use crate::ast::{JsonAccessKey, JsonAccessKind};
        let mut ast = Ast::new();
        let json = ast
            .add_expr(Expr::Literal(Literal::Null), Span::new(0, 4))
            .unwrap();
        let access = ast
            .add_expr(
                Expr::JsonAccess(
                    json,
                    JsonAccessKind::Json,
                    JsonAccessKey::Field("name".into()),
                ),
                Span::new(0, 9),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(access);
        assert_eq!(ty, Ty::Json);
    }

    #[test]
    fn infer_json_access_scalar() {
        // data..name (where data is Json)
        use crate::ast::{JsonAccessKey, JsonAccessKind};
        let mut ast = Ast::new();
        let json = ast
            .add_expr(Expr::Literal(Literal::Null), Span::new(0, 4))
            .unwrap();
        let access = ast
            .add_expr(
                Expr::JsonAccess(
                    json,
                    JsonAccessKind::Scalar,
                    JsonAccessKey::Field("name".into()),
                ),
                Span::new(0, 10),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(access);
        // Returns Option[Scalar]
        match ty {
            Ty::Option(inner) => {
                assert_eq!(*inner, Ty::Named(TypeId::SCALAR, vec![]))
            }
            _ => panic!("expected Option, got {ty:?}"),
        }
    }

    #[test]
    fn infer_json_access_dynamic_key() {
        // data->(key) where key is String
        use crate::ast::{JsonAccessKey, JsonAccessKind};
        let mut ast = Ast::new();
        let json = ast
            .add_expr(Expr::Literal(Literal::Null), Span::new(0, 4))
            .unwrap();
        let key = ast
            .add_expr(
                Expr::Literal(Literal::String("name".into())),
                Span::new(7, 13),
            )
            .unwrap();
        let access = ast
            .add_expr(
                Expr::JsonAccess(
                    json,
                    JsonAccessKind::Json,
                    JsonAccessKey::Expr(key),
                ),
                Span::new(0, 14),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(access);
        assert_eq!(ty, Ty::Json);
        // Key should be unified with String
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::String, Ty::String, _))));
    }

    #[test]
    fn infer_json_access_on_non_json() {
        // 42.name (where 42 is Int)
        use crate::ast::{JsonAccessKey, JsonAccessKind};
        let mut ast = Ast::new();
        let n = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(0, 2))
            .unwrap();
        let access = ast
            .add_expr(
                Expr::JsonAccess(
                    n,
                    JsonAccessKind::Json,
                    JsonAccessKey::Field("name".into()),
                ),
                Span::new(0, 7),
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(access);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::NotJson(_, _) => {}
            e => panic!("expected NotJson, got {e:?}"),
        }
    }

    #[test]
    fn infer_json_literal() {
        // { "name": "Alice" } as JSON
        let mut ast = Ast::new();
        let val = ast
            .add_expr(
                Expr::Literal(Literal::String("Alice".into())),
                Span::new(10, 17),
            )
            .unwrap();
        let json = ast
            .add_expr(Expr::Json(vec![("name".into(), val)]), Span::new(0, 19))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(json);
        assert_eq!(ty, Ty::Json);
    }

    // Optional field access

    #[test]
    fn infer_optional_field_on_option() {
        // opt?.name where opt is Option[{ name: String }]
        let mut ast = Ast::new();
        let var = ast
            .add_expr(Expr::Var("opt".into()), Span::new(0, 3))
            .unwrap();
        let field = ast
            .add_expr(Expr::OptionalField(var, "name".into()), Span::new(0, 9))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Create an Option type with a structural object inside
        let name_id = ctx.env_mut().intern("name");
        let inner =
            Ty::Object(std::iter::once((name_id, Ty::String)).collect());
        ctx.env_mut()
            .bind("opt", Scheme::mono(Ty::Option(Box::new(inner))));
        let ty = ctx.infer_expr(field);
        // Should return Option[String]
        match ty {
            Ty::Option(inner) => assert_eq!(*inner, Ty::String),
            _ => panic!("expected Option, got {ty:?}"),
        }
    }

    #[test]
    fn infer_optional_field_on_non_option() {
        // obj?.name where obj is { name: String }
        let mut ast = Ast::new();
        let var = ast
            .add_expr(Expr::Var("obj".into()), Span::new(0, 3))
            .unwrap();
        let field = ast
            .add_expr(Expr::OptionalField(var, "name".into()), Span::new(0, 9))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let name_id = ctx.env_mut().intern("name");
        let obj_ty =
            Ty::Object(std::iter::once((name_id, Ty::String)).collect());
        ctx.env_mut().bind("obj", Scheme::mono(obj_ty));
        let ty = ctx.infer_expr(field);
        // Should produce error (not Option)
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::Mismatch { .. } => {}
            e => panic!("expected Mismatch, got {e:?}"),
        }
    }

    // --- Union type tests ---

    #[test]
    fn expand_union_members_anonymous() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        let u = Ty::Union(vec![Ty::Int, Ty::String, Ty::Bool]);
        let members = ctx.expand_union_members(&u);
        assert_eq!(members, Some(vec![Ty::Int, Ty::String, Ty::Bool]));
    }

    #[test]
    fn expand_union_members_storable() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        let storable = Ty::Named(TypeId::STORABLE, vec![]);
        let members = ctx.expand_union_members(&storable);
        assert!(members.is_some());
        let members = members.unwrap();
        assert!(members.contains(&Ty::Bool));
        assert!(members.contains(&Ty::Int));
        assert!(members.contains(&Ty::Float));
        assert!(members.contains(&Ty::Char));
        assert!(members.contains(&Ty::String));
        assert!(members.contains(&Ty::Json));
        assert_eq!(members.len(), 6);
    }

    #[test]
    fn expand_union_members_scalar() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        let scalar = Ty::Named(TypeId::SCALAR, vec![]);
        let members = ctx.expand_union_members(&scalar);
        assert!(members.is_some());
        let members = members.unwrap();
        assert!(members.contains(&Ty::Bool));
        assert!(members.contains(&Ty::Int));
        assert!(members.contains(&Ty::Float));
        assert!(members.contains(&Ty::String));
        assert_eq!(members.len(), 4);
    }

    #[test]
    fn expand_union_members_non_union() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        // Primitive types are not unions
        assert!(ctx.expand_union_members(&Ty::Int).is_none());
        assert!(ctx.expand_union_members(&Ty::String).is_none());
        // Array is not a union
        assert!(ctx
            .expand_union_members(&Ty::Array(Box::new(Ty::Int)))
            .is_none());
    }

    #[test]
    fn is_union_member_anonymous() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        let u = Ty::Union(vec![Ty::Int, Ty::String]);
        assert!(ctx.is_union_member(&u, &Ty::Int));
        assert!(ctx.is_union_member(&u, &Ty::String));
        assert!(!ctx.is_union_member(&u, &Ty::Bool));
    }

    #[test]
    fn is_union_member_storable() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        let storable = Ty::Named(TypeId::STORABLE, vec![]);
        assert!(ctx.is_union_member(&storable, &Ty::Int));
        assert!(ctx.is_union_member(&storable, &Ty::String));
        assert!(ctx.is_union_member(&storable, &Ty::Json));
        // Array is not in Storable
        assert!(!ctx.is_union_member(&storable, &Ty::Array(Box::new(Ty::Int))));
    }

    #[test]
    fn is_union_member_non_union_returns_false() {
        let ast = Ast::new();
        let ctx = test_ctx(&ast);
        // Non-union type should return false for any member check
        assert!(!ctx.is_union_member(&Ty::Int, &Ty::Int));
    }

    #[test]
    fn ast_type_to_ty_anonymous_union() {
        let mut ast = Ast::new();
        let span = Span::new(0, 10);

        // Build `Int | String | Bool` as AstTypeExpr::Union
        let int_id = ast
            .add_type_expr(AstTypeExpr::Named("Int".into()), span)
            .unwrap();
        let str_id = ast
            .add_type_expr(AstTypeExpr::Named("String".into()), span)
            .unwrap();
        let bool_id = ast
            .add_type_expr(AstTypeExpr::Named("Bool".into()), span)
            .unwrap();
        let union_id = ast
            .add_type_expr(
                AstTypeExpr::Union(smallvec::smallvec![
                    int_id, str_id, bool_id
                ]),
                span,
            )
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.ast_type_to_ty(union_id, &HashMap::new());

        assert_eq!(ty, Ty::Union(vec![Ty::Int, Ty::String, Ty::Bool]));
    }

    #[test]
    fn ast_type_to_ty_empty_union_is_error() {
        let mut ast = Ast::new();
        let span = Span::new(0, 10);

        // Empty union
        let union_id = ast
            .add_type_expr(AstTypeExpr::Union(smallvec::smallvec![]), span)
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.ast_type_to_ty(union_id, &HashMap::new());

        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        match &ctx.errors()[0] {
            TypeError::EmptyUnion(_) => {}
            e => panic!("expected EmptyUnion, got {e:?}"),
        }
    }
}
