//! Type inference context and constraint generation.
//!
//! The inference context tracks type information during type checking:
//! expression types, type variable generation, and constraint collection.
//! Constraints are solved later via unification.

mod convert;
mod expr;
mod pattern;
mod stmt;

#[cfg(test)]
mod tests;

use std::collections::HashMap;

use nonempty::NonEmpty;
use smallvec::SmallVec;

use super::env::TypeEnv;
use super::error::{TyPrinter, TypeError};
use super::ty::{Scheme, Subst, Ty, TyVar};
use crate::ast::ExprId;
use crate::env::Environment;
use crate::intern::StringInterner;
use crate::value::{TypeExprArena, TypeRegistry};
use crate::Span;

/// A type constraint generated during inference.
///
/// Constraints represent relationships between types that must hold for the
/// program to be well-typed. They are collected during the inference pass
/// and solved together via unification.
#[derive(Clone, Debug)]
#[allow(clippy::large_enum_variant)] // Callable has SmallVec<[Ty; 4]>
pub(crate) enum Constraint {
    /// Two types must be equal.
    ///
    /// Generated by assignments, function return types, binary operators
    /// requiring matching operand types, etc.
    ///
    /// Example: `LET x: Int = e` generates `Eq(typeof(e), Int)`.
    Eq(Ty, Ty, Span),

    /// Type must be numeric (`Int` or `Float`).
    ///
    /// Generated by arithmetic operators (`+`, `-`, `*`, `/`, `%`, `**`)
    /// and unary negation. Numeric coercion (`Int` + `Float` = `Float`)
    /// is handled during constraint solving.
    ///
    /// Example: `a + b` generates `Numeric(typeof(a))` and `Numeric(typeof(b))`.
    Numeric(Ty, Span),

    /// Type must be callable with given argument types.
    ///
    /// Generated by function call expressions. During solving, the callee
    /// type is unified with `Fn(args, ret)`.
    ///
    /// Example: `f(x, y)` generates `Callable { callee: typeof(f), args: [typeof(x), typeof(y)], ret: ?r }`.
    Callable {
        callee: Ty,
        args: SmallVec<[Ty; 4]>,
        ret: Ty,
        span: Span,
    },

    /// Type can be converted to a string for display.
    ///
    /// Generated by string concatenation (`++`) and `OUTPUT` statements.
    /// In RUMPS, all types satisfy this constraint; it exists primarily
    /// to mark where implicit string coercion occurs.
    ///
    /// Example: `OUTPUT x` generates `Stringable(typeof(x))`.
    Stringable(Ty, Span),

    /// Type can be converted to JSON.
    ///
    /// Generated by `AS Json` casts, database `SET` operations, and JSON
    /// literals. Closures and functions cannot be serialized to JSON.
    ///
    /// Allowed: primitives, arrays, tuples, objects, `Option`, `Result`.
    /// Rejected: `Fn`, module functions.
    ///
    /// Example: `x AS Json` generates `Jsonable(typeof(x))`.
    Jsonable(Ty, Span),

    /// Type can be used as a database subscript key.
    ///
    /// Generated by `GET`/`SET` operations with subscripts. Valid subscript
    /// types are: `Bool`, `Int`, `Float`, `Char`, `String`, `Json`.
    ///
    /// Example: `GET local(k)` generates `Subscript(typeof(k))`.
    Subscript(Ty, Span),

    /// Type can be stored in the database.
    ///
    /// Generated by `SET` operations for the value being stored. Valid
    /// storable types match the `Storable` union: `Bool`, `Int`, `Float`,
    /// `Char`, `String`, `Json`.
    ///
    /// Example: `SET local(k) = v` generates `Storable(typeof(v))`.
    Storable(Ty, Span),

    /// Type must be unwrappable via postfix `!`.
    ///
    /// Generated by `e!` expressions. The type must be `Option[T]` or
    /// `Result[T, E]`. The `inner` field captures the extracted inner
    /// type (`T`), which becomes the result type of the unwrap.
    ///
    /// Example: `opt!` generates `Unwrappable { ty: typeof(opt), inner: ?t }`,
    /// and the expression types as `?t`.
    Unwrappable { ty: Ty, inner: Ty, span: Span },

    /// Type must have a specific field.
    ///
    /// Generated by field access on type variables (`var.field`). Unlike
    /// unifying with `Object({field: T})`, this only requires the accessed
    /// field to exist; it doesn't require all struct fields to be present.
    ///
    /// Example: `x.name` where `x: ?t` generates
    /// `HasField { base: ?t, field: "name", field_ty: ?f }`.
    HasField {
        base: Ty,
        field: crate::intern::StringId,
        field_ty: Ty,
        span: Span,
    },

    /// Type must be iterable (Array or Range).
    ///
    /// Generated by higher-order Array functions (`Array.map`, `Array.filter`,
    /// etc.) that accept both arrays and ranges. The `elem` field captures the
    /// element type yielded by iteration.
    ///
    /// Example: `Array.foreach(f, coll)` generates
    /// `Iterable { coll: typeof(coll), elem: ?e }`.
    Iterable { coll: Ty, elem: Ty, span: Span },
}

impl Constraint {
    /// Get the source span associated with this constraint.
    pub(crate) fn span(&self) -> Span {
        match self {
            Self::Eq(_, _, span)
            | Self::Numeric(_, span)
            | Self::Callable { span, .. }
            | Self::Stringable(_, span)
            | Self::Jsonable(_, span)
            | Self::Subscript(_, span)
            | Self::Storable(_, span)
            | Self::Unwrappable { span, .. }
            | Self::HasField { span, .. }
            | Self::Iterable { span, .. } => *span,
        }
    }
}

/// Type inference context.
///
/// Collects type information during the inference pass: inferred expression
/// types, type variable bindings, and constraints. After inference completes,
/// constraints are solved via unification to produce final types.
pub(crate) struct InferCtx<'a> {
    /// The AST being type-checked.
    pub(super) ast: &'a crate::ast::Ast,
    /// Registry of user-defined and builtin types.
    pub(super) registry: &'a TypeRegistry,
    /// Arena of type expressions (for converting `TypeExprId -> Ty`).
    pub(super) type_exprs: &'a TypeExprArena,
    /// Runtime environment; used to look up module function type schemes.
    pub(super) runtime_env: &'a Environment,
    /// Scoped type environment (variable -> scheme bindings).
    pub(super) env: TypeEnv,
    /// Collected constraints to be solved.
    constraints: Vec<Constraint>,
    /// Counter for generating fresh type variables.
    pub(super) next_var: u32,
    /// Inferred types for each expression.
    expr_types: HashMap<ExprId, Ty>,
    /// Type errors encountered during inference.
    errors: Vec<TypeError>,
}

impl<'a> InferCtx<'a> {
    /// Create a new inference context.
    ///
    /// The `strings` interner should be shared with the `TypeRegistry` so
    /// type name lookups produce consistent `StringId`s. The `runtime_env`
    /// is used to look up module function type schemes. The `type_exprs`
    /// arena is used to convert `TypeExprId` to `Ty` for user-defined unions.
    pub(crate) fn new(
        ast: &'a crate::ast::Ast,
        registry: &'a TypeRegistry,
        type_exprs: &'a TypeExprArena,
        runtime_env: &'a Environment,
        strings: StringInterner,
    ) -> Self {
        Self {
            ast,
            registry,
            type_exprs,
            runtime_env,
            env: TypeEnv::new(strings),
            constraints: Vec::new(),
            next_var: 0,
            expr_types: HashMap::new(),
            errors: Vec::new(),
        }
    }

    /// Generate a fresh type variable.
    pub(crate) fn fresh_var(&mut self) -> TyVar {
        let v = TyVar::new(self.next_var);
        self.next_var += 1;
        v
    }

    /// Generate a fresh type variable wrapped in `Ty::Var`.
    pub(crate) fn fresh(&mut self) -> Ty {
        Ty::Var(self.fresh_var())
    }

    /// Add a constraint to the collection.
    pub(crate) fn constrain(&mut self, c: Constraint) {
        self.constraints.push(c);
    }

    /// Add an equality constraint between two types.
    ///
    /// Shorthand for `constrain(Constraint::Eq(t1, t2, span))`.
    pub(crate) fn unify(&mut self, t1: Ty, t2: Ty, span: Span) {
        self.constrain(Constraint::Eq(t1, t2, span));
    }

    /// Record the inferred type for an expression.
    pub(crate) fn record_type(&mut self, id: ExprId, ty: Ty) {
        self.expr_types.insert(id, ty);
    }

    /// Record a type error.
    pub(crate) fn error(&mut self, e: TypeError) {
        self.errors.push(e);
    }

    /// Get the AST being type-checked.
    pub(crate) fn ast(&self) -> &crate::ast::Ast {
        self.ast
    }

    /// Get the type registry.
    pub(crate) fn registry(&self) -> &TypeRegistry {
        self.registry
    }

    /// Get a mutable reference to the type environment.
    pub(crate) fn env_mut(&mut self) -> &mut TypeEnv {
        &mut self.env
    }

    /// Get an immutable reference to the type environment.
    pub(crate) fn env(&self) -> &TypeEnv {
        &self.env
    }

    /// Get the next type variable counter (for scheme instantiation).
    pub(crate) fn next_var_mut(&mut self) -> &mut u32 {
        &mut self.next_var
    }

    /// Get the collected constraints.
    pub(crate) fn constraints(&self) -> &[Constraint] {
        &self.constraints
    }

    /// Take ownership of collected constraints, leaving an empty vec.
    pub(crate) fn take_constraints(&mut self) -> Vec<Constraint> {
        std::mem::take(&mut self.constraints)
    }

    /// Get the inferred type for an expression, if recorded.
    pub(crate) fn get_type(&self, id: ExprId) -> Option<&Ty> {
        self.expr_types.get(&id)
    }

    /// Get all expression types.
    pub(crate) fn expr_types(&self) -> &HashMap<ExprId, Ty> {
        &self.expr_types
    }

    /// Check if any errors were recorded.
    pub(crate) fn has_errors(&self) -> bool {
        !self.errors.is_empty()
    }

    /// Get the collected errors.
    pub(crate) fn errors(&self) -> &[TypeError] {
        &self.errors
    }

    /// Take ownership of collected errors, leaving an empty vec.
    pub(crate) fn take_errors(&mut self) -> Vec<TypeError> {
        std::mem::take(&mut self.errors)
    }

    /// Apply a substitution to all inferred expression types.
    ///
    /// Called after constraint solving to replace type variables with their
    /// resolved concrete types.
    pub(crate) fn apply_subst(&mut self, subst: &Subst) {
        self.expr_types
            .values_mut()
            .for_each(|ty| *ty = ty.apply(subst));
    }

    /// Check for remaining unresolved type variables and emit errors.
    ///
    /// After constraint solving and substitution application, any remaining
    /// `Ty::Var` or `Ty::Unknown` indicates incomplete inference. This emits
    /// `MissingAnnotation` errors for such cases.
    pub(crate) fn check_remaining_unknowns(&mut self) {
        let unresolved: Vec<_> = self
            .expr_types
            .iter()
            .filter(|(_, ty)| Self::has_unresolved_vars(ty))
            .map(|(id, _)| {
                self.ast.expr_span(*id).unwrap_or_else(|| Span::new(0, 0))
            })
            .collect();

        unresolved.into_iter().for_each(|span| {
            self.errors.push(TypeError::MissingAnnotation(span));
        });
    }

    /// Consume the context and return formatted errors.
    ///
    /// Unlike `into_result`, this formats type errors with proper type names
    /// using the provided registry and arena.
    pub(crate) fn into_result_formatted(
        self,
        registry: &TypeRegistry,
        arena: &crate::value::ValueArena,
    ) -> crate::Result<()> {
        NonEmpty::from_vec(self.errors).map_or(Ok(()), |errs| {
            let printer = TyPrinter::new(registry, arena, &self.env.strings);
            let formatted = errs.map(|e| e.format_with(&printer));
            let errors = formatted.map(crate::Error::FormattedType);
            Err(crate::Error::multiple(errors))
        })
    }
}
