//! Type inference context and constraint generation.
//!
//! The inference context tracks type information during type checking:
//! expression types, type variable generation, and constraint collection.
//! Constraints are solved later via unification.

use std::collections::HashMap;

use smallvec::SmallVec;

use super::env::TypeEnv;
use super::error::TypeError;
use super::ty::{Ty, TyVar};
use crate::ast::{Ast, BinOp, Expr, ExprId, Literal, UnOp};
use crate::value::TypeRegistry;
use crate::Span;

/// A type constraint generated during inference.
///
/// Constraints represent relationships between types that must hold for the
/// program to be well-typed. They are collected during the inference pass
/// and solved together via unification.
#[derive(Clone, Debug)]
pub(crate) enum Constraint {
    /// Two types must be equal.
    ///
    /// Generated by assignments, function return types, binary operators
    /// requiring matching operand types, etc.
    ///
    /// Example: `LET x: Int = e` generates `Eq(typeof(e), Int)`.
    Eq(Ty, Ty, Span),

    /// Type must be numeric (`Int` or `Float`).
    ///
    /// Generated by arithmetic operators (`+`, `-`, `*`, `/`, `%`, `**`)
    /// and unary negation. Numeric coercion (`Int` + `Float` = `Float`)
    /// is handled during constraint solving.
    ///
    /// Example: `a + b` generates `Numeric(typeof(a))` and `Numeric(typeof(b))`.
    Numeric(Ty, Span),

    /// Type must be callable with given argument types.
    ///
    /// Generated by function call expressions. During solving, the callee
    /// type is unified with `Fn(args, ret)`.
    ///
    /// Example: `f(x, y)` generates `Callable { callee: typeof(f), args: [typeof(x), typeof(y)], ret: ?r }`.
    Callable {
        callee: Ty,
        args: SmallVec<[Ty; 4]>,
        ret: Ty,
        span: Span,
    },

    /// Type can be converted to a string for display.
    ///
    /// Generated by string concatenation (`++`) and `OUTPUT` statements.
    /// In RUMPS, all types satisfy this constraint; it exists primarily
    /// to mark where implicit string coercion occurs.
    ///
    /// Example: `OUTPUT x` generates `Stringable(typeof(x))`.
    Stringable(Ty, Span),

    /// Type can be converted to JSON.
    ///
    /// Generated by `AS Json` casts, database `SET` operations, and JSON
    /// literals. Closures and functions cannot be serialized to JSON.
    ///
    /// Allowed: primitives, arrays, tuples, objects, `Option`, `Result`.
    /// Rejected: `Fn`, module functions.
    ///
    /// Example: `x AS Json` generates `Jsonable(typeof(x))`.
    Jsonable(Ty, Span),

    /// Type can be used as a database subscript key.
    ///
    /// Generated by `GET`/`SET` operations with subscripts. Valid subscript
    /// types are: `Bool`, `Int`, `Float`, `Char`, `String`, `Json`.
    ///
    /// Example: `GET local(k)` generates `Subscript(typeof(k))`.
    Subscript(Ty, Span),

    /// Type can be stored in the database.
    ///
    /// Generated by `SET` operations for the value being stored. Valid
    /// storable types match the `Storable` union: `Bool`, `Int`, `Float`,
    /// `Char`, `String`, `Json`.
    ///
    /// Example: `SET local(k) = v` generates `Storable(typeof(v))`.
    Storable(Ty, Span),

    /// Type must be unwrappable via postfix `!`.
    ///
    /// Generated by `e!` expressions. The type must be `Option[T]` or
    /// `Result[T, E]`. The `inner` field captures the extracted inner
    /// type (`T`), which becomes the result type of the unwrap.
    ///
    /// Example: `opt!` generates `Unwrappable { ty: typeof(opt), inner: ?t }`,
    /// and the expression types as `?t`.
    Unwrappable { ty: Ty, inner: Ty, span: Span },
}

impl Constraint {
    /// Get the source span associated with this constraint.
    pub(crate) fn span(&self) -> Span {
        match self {
            Self::Eq(_, _, span)
            | Self::Numeric(_, span)
            | Self::Callable { span, .. }
            | Self::Stringable(_, span)
            | Self::Jsonable(_, span)
            | Self::Subscript(_, span)
            | Self::Storable(_, span)
            | Self::Unwrappable { span, .. } => *span,
        }
    }
}

/// Type inference context.
///
/// Collects type information during the inference pass: inferred expression
/// types, type variable bindings, and constraints. After inference completes,
/// constraints are solved via unification to produce final types.
pub(crate) struct InferCtx<'a> {
    /// The AST being type-checked.
    ast: &'a Ast,
    /// Registry of user-defined and builtin types.
    registry: &'a TypeRegistry,
    /// Scoped type environment (variable -> scheme bindings).
    env: TypeEnv,
    /// Collected constraints to be solved.
    constraints: Vec<Constraint>,
    /// Counter for generating fresh type variables.
    next_var: u32,
    /// Inferred types for each expression.
    expr_types: HashMap<ExprId, Ty>,
    /// Type errors encountered during inference.
    errors: Vec<TypeError>,
}

impl<'a> InferCtx<'a> {
    /// Create a new inference context.
    pub(crate) fn new(ast: &'a Ast, registry: &'a TypeRegistry) -> Self {
        Self {
            ast,
            registry,
            env: TypeEnv::new(),
            constraints: Vec::new(),
            next_var: 0,
            expr_types: HashMap::new(),
            errors: Vec::new(),
        }
    }

    /// Generate a fresh type variable.
    pub(crate) fn fresh_var(&mut self) -> TyVar {
        let v = TyVar::new(self.next_var);
        self.next_var += 1;
        v
    }

    /// Generate a fresh type variable wrapped in `Ty::Var`.
    pub(crate) fn fresh(&mut self) -> Ty {
        Ty::Var(self.fresh_var())
    }

    /// Add a constraint to the collection.
    pub(crate) fn constrain(&mut self, c: Constraint) {
        self.constraints.push(c);
    }

    /// Add an equality constraint between two types.
    ///
    /// Shorthand for `constrain(Constraint::Eq(t1, t2, span))`.
    pub(crate) fn unify(&mut self, t1: Ty, t2: Ty, span: Span) {
        self.constrain(Constraint::Eq(t1, t2, span));
    }

    /// Record the inferred type for an expression.
    pub(crate) fn record_type(&mut self, id: ExprId, ty: Ty) {
        self.expr_types.insert(id, ty);
    }

    /// Record a type error.
    pub(crate) fn error(&mut self, e: TypeError) {
        self.errors.push(e);
    }

    /// Get the AST being type-checked.
    pub(crate) fn ast(&self) -> &Ast {
        self.ast
    }

    /// Get the type registry.
    pub(crate) fn registry(&self) -> &TypeRegistry {
        self.registry
    }

    /// Get a mutable reference to the type environment.
    pub(crate) fn env_mut(&mut self) -> &mut TypeEnv {
        &mut self.env
    }

    /// Get an immutable reference to the type environment.
    pub(crate) fn env(&self) -> &TypeEnv {
        &self.env
    }

    /// Get the next type variable counter (for scheme instantiation).
    pub(crate) fn next_var_mut(&mut self) -> &mut u32 {
        &mut self.next_var
    }

    /// Get the collected constraints.
    pub(crate) fn constraints(&self) -> &[Constraint] {
        &self.constraints
    }

    /// Take ownership of collected constraints, leaving an empty vec.
    pub(crate) fn take_constraints(&mut self) -> Vec<Constraint> {
        std::mem::take(&mut self.constraints)
    }

    /// Get the inferred type for an expression, if recorded.
    pub(crate) fn get_type(&self, id: ExprId) -> Option<&Ty> {
        self.expr_types.get(&id)
    }

    /// Get all expression types.
    pub(crate) fn expr_types(&self) -> &HashMap<ExprId, Ty> {
        &self.expr_types
    }

    /// Check if any errors were recorded.
    pub(crate) fn has_errors(&self) -> bool {
        !self.errors.is_empty()
    }

    /// Get the collected errors.
    pub(crate) fn errors(&self) -> &[TypeError] {
        &self.errors
    }

    /// Take ownership of collected errors, leaving an empty vec.
    pub(crate) fn take_errors(&mut self) -> Vec<TypeError> {
        std::mem::take(&mut self.errors)
    }

    /// Infer the type of an expression.
    ///
    /// Records the inferred type in `expr_types` and returns it. For undefined
    /// variables, records an error and returns `Ty::Error` for recovery.
    ///
    /// Currently handles Phase 4.3 expressions (literals and variables).
    /// Other expression types will be added in subsequent phases.
    pub(crate) fn infer_expr(&mut self, id: ExprId) -> Ty {
        let span = self.ast.expr_span(id).unwrap_or(Span::new(0, 0));
        let ty = self.ast.get_expr(id).map_or_else(
            || Ty::Error,
            |expr| self.infer_expr_inner(expr, span),
        );
        self.record_type(id, ty.clone());
        ty
    }

    /// Inner expression inference; dispatches on expression variant.
    fn infer_expr_inner(&mut self, expr: &Expr, span: Span) -> Ty {
        match expr {
            // Literals
            Expr::Literal(lit) => self.infer_literal(lit),

            // Unit: empty tuple
            Expr::Tuple(elems) if elems.is_empty() => Ty::Unit,

            // Variable reference
            Expr::Var(name) => self.infer_var(name, span),

            // Binary operations
            Expr::Binary(lhs, op, rhs) => {
                self.infer_binary(*lhs, *op, *rhs, span)
            }

            // Unary operations
            Expr::Unary(op, operand) => self.infer_unary(*op, *operand, span),

            // Range expressions
            Expr::Range(start, end, _inclusive) => {
                let start_ty = self.infer_expr(*start);
                let end_ty = self.infer_expr(*end);
                self.unify(start_ty, Ty::Int, span);
                self.unify(end_ty, Ty::Int, span);
                Ty::Range
            }

            // Other expressions handled in later phases
            _ => Ty::Error,
        }
    }

    /// Infer type of a literal.
    fn infer_literal(&self, lit: &Literal) -> Ty {
        match lit {
            Literal::Bool(_) => Ty::Bool,
            Literal::Int(_) => Ty::Int,
            Literal::Float(_) => Ty::Float,
            Literal::Char(_) => Ty::Char,
            Literal::String(_) => Ty::String,
            Literal::Null => Ty::Json,
            Literal::Unit => Ty::Unit,
        }
    }

    /// Infer type of a variable reference.
    ///
    /// Looks up the variable in the type environment and instantiates its
    /// scheme with fresh type variables. If undefined, records an error
    /// and returns `Ty::Error`.
    fn infer_var(&mut self, name: &str, span: Span) -> Ty {
        match self.env.lookup(name) {
            Some(scheme) => scheme.instantiate(&mut self.next_var),
            None => {
                self.error(TypeError::UndefinedVar(name.to_string(), span));
                Ty::Error
            }
        }
    }

    /// Infer type of a binary operation.
    ///
    /// Generates appropriate constraints based on the operator and returns
    /// the result type.
    fn infer_binary(
        &mut self,
        lhs_id: ExprId,
        op: BinOp,
        rhs_id: ExprId,
        span: Span,
    ) -> Ty {
        let lhs_ty = self.infer_expr(lhs_id);
        let rhs_ty = self.infer_expr(rhs_id);

        match op {
            // Arithmetic: both numeric, result depends on operand types
            BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Mod | BinOp::Pow => {
                self.constrain(Constraint::Numeric(lhs_ty.clone(), span));
                self.constrain(Constraint::Numeric(rhs_ty.clone(), span));
                // If either is Float, result is Float; else fresh numeric
                if lhs_ty == Ty::Float || rhs_ty == Ty::Float {
                    Ty::Float
                } else if lhs_ty == Ty::Int && rhs_ty == Ty::Int {
                    Ty::Int
                } else {
                    // One or both are type vars; result is fresh numeric
                    let result = self.fresh();
                    self.constrain(Constraint::Numeric(result.clone(), span));
                    result
                }
            }

            // Division always returns Float
            BinOp::Div => {
                self.constrain(Constraint::Numeric(lhs_ty, span));
                self.constrain(Constraint::Numeric(rhs_ty, span));
                Ty::Float
            }

            // Floor division always returns Int
            BinOp::FloorDiv => {
                self.constrain(Constraint::Numeric(lhs_ty, span));
                self.constrain(Constraint::Numeric(rhs_ty, span));
                Ty::Int
            }

            // Comparison: operands must unify, result is Bool
            BinOp::Eq
            | BinOp::Ne
            | BinOp::Lt
            | BinOp::Gt
            | BinOp::Le
            | BinOp::Ge => {
                self.unify(lhs_ty, rhs_ty, span);
                Ty::Bool
            }

            // Logical: both must be Bool, result is Bool
            BinOp::And | BinOp::Or => {
                self.unify(lhs_ty, Ty::Bool, span);
                self.unify(rhs_ty, Ty::Bool, span);
                Ty::Bool
            }

            // String concatenation: lhs is String, rhs is Stringable
            BinOp::Concat => {
                self.unify(lhs_ty, Ty::String, span);
                self.constrain(Constraint::Stringable(rhs_ty, span));
                Ty::String
            }

            // Coalesce: lhs is Option[T] or Result[T, E], rhs unifies with T
            BinOp::Coalesce => {
                let inner = self.fresh();
                self.constrain(Constraint::Unwrappable {
                    ty: lhs_ty,
                    inner: inner.clone(),
                    span,
                });
                self.unify(rhs_ty, inner.clone(), span);
                inner
            }

            // Pipe: rhs is callable with lhs as argument
            BinOp::Pipe => {
                let result = self.fresh();
                self.constrain(Constraint::Callable {
                    callee: rhs_ty,
                    args: smallvec::smallvec![lhs_ty],
                    ret: result.clone(),
                    span,
                });
                result
            }
        }
    }

    /// Infer type of a unary operation.
    ///
    /// Generates appropriate constraints based on the operator and returns
    /// the result type.
    fn infer_unary(&mut self, op: UnOp, operand_id: ExprId, span: Span) -> Ty {
        let operand_ty = self.infer_expr(operand_id);

        match op {
            // Negation: operand must be numeric, result is same type
            UnOp::Neg => {
                self.constrain(Constraint::Numeric(operand_ty.clone(), span));
                operand_ty
            }

            // Logical not: operand must be Bool, result is Bool
            UnOp::Not => {
                self.unify(operand_ty, Ty::Bool, span);
                Ty::Bool
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test helper: create minimal context components for testing.
    ///
    /// Returns context state without needing full `InferCtx` construction,
    /// since `TypeRegistry::new` requires mutable arenas.
    struct TestState {
        env: TypeEnv,
        constraints: Vec<Constraint>,
        next_var: u32,
        expr_types: HashMap<ExprId, Ty>,
        errors: Vec<TypeError>,
    }

    impl TestState {
        fn new() -> Self {
            Self {
                env: TypeEnv::new(),
                constraints: Vec::new(),
                next_var: 0,
                expr_types: HashMap::new(),
                errors: Vec::new(),
            }
        }

        fn with_next_var(mut self, n: u32) -> Self {
            self.next_var = n;
            self
        }

        fn fresh_var(&mut self) -> TyVar {
            let v = TyVar::new(self.next_var);
            self.next_var += 1;
            v
        }

        fn fresh(&mut self) -> Ty {
            Ty::Var(self.fresh_var())
        }

        fn constrain(&mut self, c: Constraint) {
            self.constraints.push(c);
        }

        fn unify(&mut self, t1: Ty, t2: Ty, span: Span) {
            self.constrain(Constraint::Eq(t1, t2, span));
        }

        fn error(&mut self, e: TypeError) {
            self.errors.push(e);
        }

        fn has_errors(&self) -> bool {
            !self.errors.is_empty()
        }
    }

    #[test]
    fn fresh_var_increments() {
        let mut state = TestState::new();

        let v0 = state.fresh_var();
        let v1 = state.fresh_var();
        let v2 = state.fresh_var();

        assert_eq!(v0, TyVar::new(0));
        assert_eq!(v1, TyVar::new(1));
        assert_eq!(v2, TyVar::new(2));
        assert_eq!(state.next_var, 3);
    }

    #[test]
    fn fresh_returns_ty_var() {
        let mut state = TestState::new().with_next_var(10);

        let ty = state.fresh();
        assert_eq!(ty, Ty::Var(TyVar::new(10)));
    }

    #[test]
    fn constrain_collects() {
        let mut state = TestState::new();

        let span = Span::new(0, 5);
        state.constrain(Constraint::Numeric(Ty::Int, span));
        state.constrain(Constraint::Eq(Ty::Int, Ty::Float, span));

        assert_eq!(state.constraints.len(), 2);
    }

    #[test]
    fn unify_adds_eq_constraint() {
        let mut state = TestState::new();

        let span = Span::new(0, 5);
        state.unify(Ty::Int, Ty::String, span);

        assert_eq!(state.constraints.len(), 1);
        match &state.constraints[0] {
            Constraint::Eq(t1, t2, s) => {
                assert_eq!(*t1, Ty::Int);
                assert_eq!(*t2, Ty::String);
                assert_eq!(*s, span);
            }
            _ => panic!("expected Eq constraint"),
        }
    }

    #[test]
    fn error_collects() {
        let mut state = TestState::new();

        assert!(!state.has_errors());

        let span = Span::new(0, 5);
        state.error(TypeError::UndefinedVar("x".to_string(), span));

        assert!(state.has_errors());
        assert_eq!(state.errors.len(), 1);
    }

    #[test]
    fn constraint_span() {
        let span = Span::new(10, 20);

        assert_eq!(Constraint::Eq(Ty::Int, Ty::Int, span).span(), span);
        assert_eq!(Constraint::Numeric(Ty::Int, span).span(), span);
        assert_eq!(
            Constraint::Callable {
                callee: Ty::Int,
                args: SmallVec::new(),
                ret: Ty::Int,
                span
            }
            .span(),
            span
        );
        assert_eq!(Constraint::Stringable(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Jsonable(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Subscript(Ty::Int, span).span(), span);
        assert_eq!(Constraint::Storable(Ty::Int, span).span(), span);
        assert_eq!(
            Constraint::Unwrappable {
                ty: Ty::Int,
                inner: Ty::Int,
                span
            }
            .span(),
            span
        );
    }

    use crate::typecheck::Scheme;
    use crate::value::{TypeExprArena, ValueArena};

    /// Create an `InferCtx` for testing with a minimal AST.
    fn test_ctx(ast: &Ast) -> InferCtx<'_> {
        let mut arena = ValueArena::new();
        let mut type_exprs = TypeExprArena::new();
        let registry = TypeRegistry::new(&mut arena, &mut type_exprs).unwrap();
        // Leak to get 'static lifetime; tests don't need to clean up
        let registry = Box::leak(Box::new(registry));
        InferCtx::new(ast, registry)
    }

    /// Create an AST with a single expression.
    fn ast_with_expr(expr: Expr) -> (Ast, ExprId) {
        let mut ast = Ast::new();
        let id = ast.add_expr(expr, Span::new(0, 10)).unwrap();
        (ast, id)
    }

    #[test]
    fn infer_literal_bool_true() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Bool(true)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_literal_bool_false() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Bool(false)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_literal_int() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Int(42)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_literal_float() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Float(3.14)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_literal_char() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Char('x')));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Char);
    }

    #[test]
    fn infer_literal_string() {
        let (ast, id) =
            ast_with_expr(Expr::Literal(Literal::String("hello".into())));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
    }

    #[test]
    fn infer_literal_null() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Null));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Json);
    }

    #[test]
    fn infer_literal_unit() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Unit));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Unit);
    }

    #[test]
    fn infer_empty_tuple_as_unit() {
        let (ast, id) = ast_with_expr(Expr::Tuple(smallvec::smallvec![]));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Unit);
    }

    #[test]
    fn infer_var_found() {
        let (ast, id) = ast_with_expr(Expr::Var("x".into()));
        let mut ctx = test_ctx(&ast);
        // Bind "x" to Int in the environment
        ctx.env_mut().bind("x", Scheme::mono(Ty::Int));
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
        assert!(!ctx.has_errors());
    }

    #[test]
    fn infer_var_not_found() {
        let (ast, id) = ast_with_expr(Expr::Var("undefined".into()));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Error);
        assert!(ctx.has_errors());
        assert_eq!(ctx.errors().len(), 1);
        match &ctx.errors()[0] {
            TypeError::UndefinedVar(name, _) => assert_eq!(name, "undefined"),
            e => panic!("expected UndefinedVar, got {e:?}"),
        }
    }

    #[test]
    fn infer_var_instantiates_scheme() {
        let (ast, id) = ast_with_expr(Expr::Var("id".into()));
        let mut ctx = test_ctx(&ast);
        // Bind "id" to a polymorphic scheme: forall a. a -> a
        // Use a high index to avoid collision with fresh vars (which start at 0)
        let a = TyVar::new(1000);
        let scheme = Scheme {
            vars: vec![a],
            ty: Ty::Fn(vec![Ty::Var(a)], Box::new(Ty::Var(a))),
        };
        ctx.env_mut().bind("id", scheme);
        let ty = ctx.infer_expr(id);
        // Should get Fn with fresh type variable (not the original `a`)
        match ty {
            Ty::Fn(params, ret) => {
                assert_eq!(params.len(), 1);
                // The fresh variable should have a different index
                match (&params[0], ret.as_ref()) {
                    (Ty::Var(v1), Ty::Var(v2)) => {
                        assert_eq!(v1, v2); // Same fresh variable
                        assert_ne!(*v1, a); // Different from original (1000)
                    }
                    _ => panic!("expected Var types"),
                }
            }
            _ => panic!("expected Fn type, got {ty:?}"),
        }
    }

    #[test]
    fn infer_expr_records_type() {
        let (ast, id) = ast_with_expr(Expr::Literal(Literal::Int(42)));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ctx.get_type(id), Some(&ty));
    }

    /// Helper to create AST with binary expression from two literals.
    fn ast_with_binary(lhs: Literal, op: BinOp, rhs: Literal) -> (Ast, ExprId) {
        let mut ast = Ast::new();
        let l = ast.add_expr(Expr::Literal(lhs), Span::new(0, 1)).unwrap();
        let r = ast.add_expr(Expr::Literal(rhs), Span::new(4, 5)).unwrap();
        let bin = ast
            .add_expr(Expr::Binary(l, op, r), Span::new(0, 5))
            .unwrap();
        (ast, bin)
    }

    // Arithmetic operators

    #[test]
    fn infer_add_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Add, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
        // Should have 2 Numeric constraints for operands
        let numerics: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Numeric(_, _)))
            .collect();
        assert_eq!(numerics.len(), 2);
    }

    #[test]
    fn infer_add_float_float() {
        let (ast, id) = ast_with_binary(
            Literal::Float(1.0),
            BinOp::Add,
            Literal::Float(2.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_add_int_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Add, Literal::Float(2.0));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float); // Widening to Float
    }

    #[test]
    fn infer_add_float_int() {
        let (ast, id) =
            ast_with_binary(Literal::Float(1.0), BinOp::Add, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_sub_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Sub, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_mul_int_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(2), BinOp::Mul, Literal::Float(3.5));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_mod_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::Mod, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_pow_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(2), BinOp::Pow, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int);
    }

    #[test]
    fn infer_pow_float_int() {
        let (ast, id) =
            ast_with_binary(Literal::Float(2.0), BinOp::Pow, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float);
    }

    // Division operators

    #[test]
    fn infer_div_int_int_returns_float() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::Div, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Float); // Division always Float
    }

    #[test]
    fn infer_floor_div_int_int_returns_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(10), BinOp::FloorDiv, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int); // Floor division always Int
    }

    #[test]
    fn infer_floor_div_float_float_returns_int() {
        let (ast, id) = ast_with_binary(
            Literal::Float(10.0),
            BinOp::FloorDiv,
            Literal::Float(3.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Int); // Floor division always Int
    }

    // Comparison operators

    #[test]
    fn infer_eq_int_int() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Eq, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
        // Should have Eq constraint unifying operands
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(_, _, _))));
    }

    #[test]
    fn infer_ne_returns_bool() {
        let (ast, id) = ast_with_binary(
            Literal::String("a".into()),
            BinOp::Ne,
            Literal::String("b".into()),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_lt_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(1), BinOp::Lt, Literal::Int(2));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_gt_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Gt, Literal::Int(3));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_le_returns_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Float(1.0),
            BinOp::Le,
            Literal::Float(2.0),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    #[test]
    fn infer_ge_returns_bool() {
        let (ast, id) =
            ast_with_binary(Literal::Int(5), BinOp::Ge, Literal::Int(5));
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    // Logical operators

    #[test]
    fn infer_and_bool_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Bool(true),
            BinOp::And,
            Literal::Bool(false),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
        // Should have 2 Eq constraints unifying operands with Bool
        let eqs: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Eq(_, Ty::Bool, _)))
            .collect();
        assert_eq!(eqs.len(), 2);
    }

    #[test]
    fn infer_or_bool_bool() {
        let (ast, id) = ast_with_binary(
            Literal::Bool(false),
            BinOp::Or,
            Literal::Bool(true),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::Bool);
    }

    // String concatenation

    #[test]
    fn infer_concat_string_string() {
        let (ast, id) = ast_with_binary(
            Literal::String("hello".into()),
            BinOp::Concat,
            Literal::String(" world".into()),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
        // Should have Stringable constraint for rhs
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Stringable(_, _))));
    }

    #[test]
    fn infer_concat_string_int() {
        // String ++ Int is valid; Int is Stringable
        let (ast, id) = ast_with_binary(
            Literal::String("count: ".into()),
            BinOp::Concat,
            Literal::Int(42),
        );
        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(id);
        assert_eq!(ty, Ty::String);
        // Stringable constraint on Int
        let stringables: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Stringable(Ty::Int, _)))
            .collect();
        assert_eq!(stringables.len(), 1);
    }

    // Coalesce

    #[test]
    fn infer_coalesce_creates_unwrappable_constraint() {
        // For coalesce, lhs needs to be Option[T] or Result[T, E]
        // Here we test with a variable that would be Option[Int]
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Var("opt".into()), Span::new(0, 3))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(7, 8))
            .unwrap();
        let coal = ast
            .add_expr(Expr::Binary(lhs, BinOp::Coalesce, rhs), Span::new(0, 8))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "opt" to Option[Int]
        ctx.env_mut()
            .bind("opt", Scheme::mono(Ty::Option(Box::new(Ty::Int))));
        let ty = ctx.infer_expr(coal);

        // Result should be fresh var unified with rhs (Int)
        match ty {
            Ty::Var(_) => {
                // Should have Unwrappable constraint
                assert!(ctx
                    .constraints()
                    .iter()
                    .any(|c| matches!(c, Constraint::Unwrappable { .. })));
                // And Eq constraint unifying inner with rhs
                assert!(ctx
                    .constraints()
                    .iter()
                    .any(|c| matches!(c, Constraint::Eq(_, _, _))));
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    // Pipe

    #[test]
    fn infer_pipe_creates_callable_constraint() {
        // 42 |> f should add Callable constraint on f
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(0, 2))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Var("f".into()), Span::new(6, 7))
            .unwrap();
        let pipe = ast
            .add_expr(Expr::Binary(lhs, BinOp::Pipe, rhs), Span::new(0, 7))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "f" to Int -> String
        ctx.env_mut().bind(
            "f",
            Scheme::mono(Ty::Fn(vec![Ty::Int], Box::new(Ty::String))),
        );
        let ty = ctx.infer_expr(pipe);

        // Result is fresh var
        match ty {
            Ty::Var(_) => {
                // Should have Callable constraint
                let callables: Vec<_> = ctx
                    .constraints()
                    .iter()
                    .filter(|c| matches!(c, Constraint::Callable { .. }))
                    .collect();
                assert_eq!(callables.len(), 1);
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }

    // Unary operators

    #[test]
    fn infer_neg_int() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Int(42)), Span::new(1, 3))
            .unwrap();
        let neg = ast
            .add_expr(Expr::Unary(UnOp::Neg, operand), Span::new(0, 3))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(neg);
        assert_eq!(ty, Ty::Int);
        // Should have Numeric constraint
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Numeric(Ty::Int, _))));
    }

    #[test]
    fn infer_neg_float() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Float(3.14)), Span::new(1, 5))
            .unwrap();
        let neg = ast
            .add_expr(Expr::Unary(UnOp::Neg, operand), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(neg);
        assert_eq!(ty, Ty::Float);
    }

    #[test]
    fn infer_not_bool() {
        let mut ast = Ast::new();
        let operand = ast
            .add_expr(Expr::Literal(Literal::Bool(true)), Span::new(1, 5))
            .unwrap();
        let not = ast
            .add_expr(Expr::Unary(UnOp::Not, operand), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(not);
        assert_eq!(ty, Ty::Bool);
        // Should have Eq constraint unifying operand with Bool
        assert!(ctx
            .constraints()
            .iter()
            .any(|c| matches!(c, Constraint::Eq(Ty::Bool, Ty::Bool, _))));
    }

    // Range

    #[test]
    fn infer_range_int_int() {
        let mut ast = Ast::new();
        let start = ast
            .add_expr(Expr::Literal(Literal::Int(0)), Span::new(0, 1))
            .unwrap();
        let end = ast
            .add_expr(Expr::Literal(Literal::Int(10)), Span::new(4, 6))
            .unwrap();
        let range = ast
            .add_expr(Expr::Range(start, end, false), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(range);
        assert_eq!(ty, Ty::Range);
        // Should have 2 Eq constraints unifying operands with Int
        let int_constraints: Vec<_> = ctx
            .constraints()
            .iter()
            .filter(|c| matches!(c, Constraint::Eq(Ty::Int, Ty::Int, _)))
            .collect();
        assert_eq!(int_constraints.len(), 2);
    }

    #[test]
    fn infer_range_inclusive_int_int() {
        let mut ast = Ast::new();
        let start = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(0, 1))
            .unwrap();
        let end = ast
            .add_expr(Expr::Literal(Literal::Int(5)), Span::new(5, 6))
            .unwrap();
        let range = ast
            .add_expr(Expr::Range(start, end, true), Span::new(0, 6))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        let ty = ctx.infer_expr(range);
        assert_eq!(ty, Ty::Range); // Same type regardless of inclusive flag
    }

    // Arithmetic with type variables

    #[test]
    fn infer_add_with_var_produces_fresh_numeric() {
        // x + 1 where x is a type variable
        let mut ast = Ast::new();
        let lhs = ast
            .add_expr(Expr::Var("x".into()), Span::new(0, 1))
            .unwrap();
        let rhs = ast
            .add_expr(Expr::Literal(Literal::Int(1)), Span::new(4, 5))
            .unwrap();
        let add = ast
            .add_expr(Expr::Binary(lhs, BinOp::Add, rhs), Span::new(0, 5))
            .unwrap();

        let mut ctx = test_ctx(&ast);
        // Bind "x" to a fresh type variable via polymorphic scheme
        let a = TyVar::new(1000);
        ctx.env_mut().bind(
            "x",
            Scheme {
                vars: vec![a],
                ty: Ty::Var(a),
            },
        );

        let ty = ctx.infer_expr(add);
        // Result should be a fresh type variable (since one operand is var)
        match ty {
            Ty::Var(_) => {
                // Should have 3 Numeric constraints: lhs, rhs, result
                let numerics: Vec<_> = ctx
                    .constraints()
                    .iter()
                    .filter(|c| matches!(c, Constraint::Numeric(_, _)))
                    .collect();
                assert_eq!(numerics.len(), 3);
            }
            _ => panic!("expected type variable, got {ty:?}"),
        }
    }
}
