[package]
name = "rumps"
version = "0.0.1"
edition = "2021"

[dependencies]
rumps-types = { path = "../rumps-types" }
rumps-storage = { path = "../rumps-storage", default-features = false }
rumps-derive = { path = "../rumps-derive", optional = true }
csv = { version = "1", optional = true }
tokio = { workspace = true, optional = true }
futures = { workspace = true, optional = true }

[dev-dependencies]
tokio-test = "0.4"

[features]
default = ["derive"]
derive = ["rumps-derive", "rumps-storage/derive"]
examples = ["dep:csv", "dep:tokio", "dep:futures"]

[[example]]
name = "medical"
required-features = ["examples"]

[[example]]
name = "financial"
required-features = ["examples"]

[lints.clippy]
obfuscated_if_else = "allow"
option_map_unit_fn = "allow"
type_complexity = "allow"
use_self = "warn"
unwrap_used = "deny"
expect_used = "deny"
